### ISSUE TITLE
Question: State of the project, release expected soon?

### ISSUE THREAD

**Issue by strongly-typed** [IronLanguages/ironpython3#1027]
Dear all contributors,

thank you very much for your effort you put into IronPython2 and IronPython3. As Python2.7 is now EOL, I am facing the challenge to either migrate from IronPython2 to 3 or commission a new implementation of the software we use in a different technology. I fully understand that this project is probably mostly run in spare time and resources are limited, although my questions and bugs in IronPython2 were promptly addressed.

My humble question is this: Is there a release on the horizon? When I take a look at the [growing number of issues](https://9-volt.github.io/bug-life/?repo=IronLanguages/ironpython3) what timeline for releases and readiness for production can I expect?

Thank you very much in advance,

Sascha

**Comment by simplicbe** [comment]
Hey @strongly-typed,

I think IronPython 3 is very important and interesting for many. Maybe there is the possibility to put permanent development power into the project through a number of companies or other resources. I've spoken to some companies to invest in this project and they are very interested, so maybe this is also a way to go. What do the others think about it?

**Comment by slozier** [comment]
While the number of issues is growing, a lot of them are just documenting edge cases that you're unlikely to encounter during normal use (and that also exist with IronPython 2). In fact, test coverage is actually better than it is with IronPython 2 and there are less compatibility issues with CPython.

The major blocker right now is proper handling of the `nonlocal` keyword. Once that and [a few other issues](https://github.com/IronLanguages/ironpython3/milestone/1) are resolved I would be happy to do some sort of release.

As you mentioned, it's a spare time project for me and the other contributors so it's really hard to give a timeline. My hope is to have something ready before the end of the year, but I can't make any promises to that effect.

**Comment by slozier** [comment]
@xia-rongyan Doing some final tests with the current build and assuming I don't run into any blocking issues I expect to do a release before the end of the month.

**Comment by slozier** [comment]
The first release is now available at https://github.com/IronLanguages/ironpython3/releases

**Comment by slozier** [comment]
@aisk https://www.nuget.org/packages/IronPython/3.4.0-alpha1

**Comment by aisk** [comment]
Sorry for missing it, thanks!

**Comment by strongly-typed** [comment]
Dear all,

great to see the alpha release. Was able to run it and test is out.

Unfortunately, Python 3.4 was EOL'ed March 2019 and infrastructure and support packages introduce breaking changes, e.g.  [setuptools dropped support for Python 3.4](https://github.com/pypa/setuptools/pull/1908).

What is the outlook? (Iron)Python without the packages and support tools is somehow limited in its usage.

Any plans to keep up with any more recent and supported Python versions?
