### ISSUE TITLE
Cannot quit console via Ctrl-D

### ISSUE THREAD

**Issue by isaiah** [IronLanguages/ironpython3#1069]
Tried `exit()` as well, have to use ctrl-c to force quit on Linux

**Comment by slozier** [comment]
Hmm, ctrl-D works for me but it looks like you have to hit enter after (which is kind of weird).

The `exit` command comes from the standard library so won't be available if the standard library isn't loaded.

**Comment by slozier** [comment]
See https://github.com/IronLanguages/ironpython2/issues/156

**Comment by BCSharp** [comment]
Fixed by 199b562a.
