### ISSUE TITLE
When will it be released?

### ISSUE THREAD

**Issue by kasajian** [IronLanguages/ironpython3#1072]
I realize you don't know and it's hard to predict.
But we can make decisions based on time frame.  For instance, if you were to say there's a 90% chance it's released in the next 24 months, vs. 10% chance, that may allow us to make long term strategic investments.

So opposed to selecting a different technology today and have to migrate to IronPython later.

When we ask when will it be released, we're not looking for a date.  A year would be nice, along with a confidence factor.

If I ask will be released in 5 years, and you say you don't know, then I can just go away.

**Comment by simplicbe** [comment]
@kasajian a discussion is already existing: https://github.com/IronLanguages/ironpython3/issues/1027

**Comment by slozier** [comment]
Closing this thread in favor of the other one. At the rate things are going I expect an alpha release within the next few months.
