### ISSUE TITLE
Running python with invalid option does not output proper message

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#1074]
For example, `ipy -foo` fails with:
> File -foo does not exist.

instead of:
> Unknown option: -f
usage: C:\Python34\python.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

**Comment by BCSharp** [comment]
Another example with a valid option but invalid option argument:

```
PS> ipy -X:Frame
File -X:Frame does not exist.
PS> ipy -X:Frames
IronPython 3.4.0a1 (3.4.0.0001)
[.NETFramework,Version=v4.6 on .NET Framework 4.8.4300.0 (64-bit)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by slozier** [comment]
Something else I noticed the other day, CPython uses `-X blabla" for implementation-specific options, we should consider dropping the `:` and doing the same.

**Comment by BCSharp** [comment]
Agree.
