### ISSUE TITLE
Aggregated command line options are not properly recognized

### ISSUE THREAD

**Issue by BCSharp** [IronLanguages/ironpython3#1075]
For example `ipy -bus` fails with:

> File -bus does not exist.

instead of being processed as `ipy -b -u -s`.

In some cases, aggregate options are recognized as special cases, for instance `-bb` as `-b -b` and `-OO`, but only because they are being seen as distinct explicitly defined options. Instead of this handling, all options should be processed as single letter, some with an optional argument after a space or a colon.

This option processing behaviour is expected by Python tools and modules. For instance, `ipy -m venv` fails because as part of the virtual environment creation, the following command is run:

    ipy -Im ensurepip --upgrade --default-pip

Which fails with `File -Im does not exist` rather than being interpreted as ` ipy -I -m ensurepip --upgrade --default-pip`

Related issue: #1074

**Comment by slozier** [comment]
Patched `venv` in https://github.com/IronLanguages/ironpython3/pull/1206. Should revert once this is fixed.
