### ISSUE TITLE
When do you think IronPython3 will be ready ?

### ISSUE THREAD

**Issue by mdengusiak** [IronLanguages/ironpython3#112]
Hi, When do you think IronPython3 will be in-use/ ready and as popular as currently version IronPython 2.7.7rc2?

**Comment by slide** [comment]
This question is probably better suited to the mailing list which you can subscribe to [here](https://mail.python.org/mailman/listinfo/ironpython-users). We are trying to get a good final 2.7 release out and then will be focusing on IronPython3. I would hope to have something usable by the end of the year (there are many changes we need to implement).

**Comment by simplicbe** [comment]
@mdengusiak you can also join our Gitter channel and join our conversations.

**Comment by mdengusiak** [comment]
thanks a lot for quick reply, this sounds great
ps.  sorry for asking in the wrong place
