### ISSUE TITLE
Metaclass __prepare__ executed out of order

### ISSUE THREAD

**Issue by BCSharp** [IronLanguages/ironpython3#1154]
According to [PEP 3115](https://www.python.org/dev/peps/pep-3115/), the `__prepare__` method defined in a metaclass should be executed early, before the main body of the class using that metaclass as its type. But currently `__prepare__` is executed after (and twice) so the dictionary-like objects it creates is not being used while the body of the class is being evaluated.

Example:

```python
class Meta(type):
    @classmethod
    def __prepare__(metacls, name, bases):
        print("__prepare__ called")
        return dict(x="metaclass prepared")

class C(metaclass=Meta):
    print("class body executing")
    assert 'x' in dir() # IronPython fails

assert 'x' in dir(C) # passes if the previous assert is commented out
```

CPython:
```
__prepare__ called
class body executing
```

IronPython (after removing the assertions):
```
class body executing
__prepare__ called
__prepare__ called
```

**Comment by slozier** [comment]
Looks like I'm the one to blame for the double `__prepare__` calls (https://github.com/IronLanguages/ironpython3/pull/174). Although I seemed to have been aware of the issues with it. 😃
