### ISSUE TITLE
How can we use Python 3.5 instead of 3?

### ISSUE THREAD

**Issue by pkonovalov-softheme** [IronLanguages/ironpython3#116]

**Comment by simplicbe** [comment]
What do you mean? IP3 first version will be compatible with python v3.5.

**Comment by slide** [comment]
We're planning on being compatible to 3.6

**Comment by simplicbe** [comment]
Oh sorry, I've wrote 3.5, for sure 3.6 is correct.

**Comment by pkonovalov-softheme** [comment]
I have build ironpython3 from sources.. but looks like it is trying to use Python 3.0 interpreter.. I have Python 3.5 code and want to use Python 3.5 interpreter.. can I do this now?

**Comment by slide** [comment]
IronPython3 is not ready for any use yet.
