### ISSUE TITLE
Installing via Nuget leads to compile error on .NET 5 or .NET 6

### ISSUE THREAD

**Issue by Rainmaker52** [IronLanguages/ironpython3#1227]
### Prerequisites

* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

### Description

(Warning; new IronPython user).

After adding IronPython 3.4.0-alpha1 and IronPython.StdLib 3.4.0-alpha1 to my WPF project, the project refuses to compile, stating it cannot find the assembly.

Removing the 3.4.0-alpha1 version and instead installing 2.7.11, makes it possible to compile the project again.

This only happens when TargetFramework is set to net5.0-windows or net6.0-windows. .NET Core 3.1 allows the project to compile.

> 
> Build started...
> 1>------ Build started: Project: WpfApp2, Configuration: Debug Any CPU ------
> 1>Build started 18-5-2021 10:08:06.
> 1>Target _CheckForNETCoreSdkIsPreview:
> 1>  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
> 1>Target MarkupCompilePass1:
> 1>  C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(222,9): error MC1000: Unknown build error, 'Could not find assembly 'IronPython, Version=3.4.0.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.'
> 1>Done building target "MarkupCompilePass1" in project "WpfApp2.csproj" -- FAILED.
> 1>
> 1>Done building project "WpfApp2.csproj" -- FAILED.
> 1>
> 1>Build FAILED.
> 1>
> 1>C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(222,9): error MC1000: Unknown build error, 'Could not find assembly 'IronPython, Version=3.4.0.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.' 
> 1>    0 Warning(s)
> 1>    1 Error(s)
> 1>
> 1>Time Elapsed 00:00:00.96
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> 

### Steps to Reproduce

1. Open VS2019
2. Create a new WPF App
3. Add IronPython as a Nuget reference
4. Try to compile and run

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `ipy -V`.

**Comment by slozier** [comment]
Thanks for the report! I wasn't planning on including net5.0 assemblies in the nuget package (they're essentially identical to the netcoreapp3.1 ones) but it looks like I forgot to exclude them while packaging. Furthermore the net5.0-windows folder in the package only contains the Wpf binary which is why it's not finding the reference to IronPython. I'll make sure this gets fixed for the next release.

As a workaround you could try something like:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamicLanguageRuntime" Version="1.3.0" />
    <PackageReference Include="IronPython" ExcludeAssets="Compile" Version="3.4.0-alpha1" GeneratePathProperty="true" />
    <Reference Include="IronPython">
      <HintPath>$(NuGetPackageRoot)ironpython\3.4.0-alpha1\lib\netcoreapp3.1\IronPython.dll</HintPath>
    </Reference>
    <Reference Include="IronPython.Modules">
      <HintPath>$(NuGetPackageRoot)ironpython\3.4.0-alpha1\lib\netcoreapp3.1\IronPython.Modules.dll</HintPath>
    </Reference>
    <Reference Include="IronPython.Wpf">
      <HintPath>$(NuGetPackageRoot)ironpython\3.4.0-alpha1\lib\netcoreapp3.1\IronPython.Wpf.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
```
