### ISSUE TITLE
Application crashes if there is infinite recursion at Python code.

### ISSUE THREAD

**Issue by ptomin** [IronLanguages/ironpython3#1234]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

### Description

Embedded `IronPython` causes crash of application if there is infinite recursion. It should raise `RecursionError`
 (since Python 3.5) or `RuntimeError` (before Python 3.5) instead.

### Steps to Reproduce
Following `C#` code can be used to reproduce it:
```
    var engine = IronPython.Hosting.Python.CreateEngine();
    var script = @"
def func():
    func()

try:
    func()
except Exception:
    print('Failed to call func')
";
    engine.Execute(script);
```

**Expected behavior:**
Printing "Failed to call func".

**Actual behavior:**
Application exited with Access violation Error.

### Versions

3.4.0-alpha

**Comment by slozier** [comment]
You can set a recursion limit as follows:
```c#
var engine = IronPython.Hosting.Python.CreateEngine(new Dictionary<string, object>() { { "RecursionLimit", 100 } });
var script = @"
def func():
    func()

try:
    func()
except Exception:
    print('Failed to call func')
";
engine.Execute(script);
```
and via the command line the equivalent options is `-X:MaxRecursion 100`.

**Comment by ptomin** [comment]
Good work around! Thanks, @slozier.
So shouldn't 100 be set as recursion limit by default to avoid such crashes?

**Comment by slozier** [comment]
The reason it's off by default is that there is a significant performance cost in having set a recursion limit. I guess the documentation should be updated to note the difference and how to opt-in.

**Comment by slozier** [comment]
Resolved via documentation:
https://github.com/IronLanguages/ironpython3/blob/master/Documentation/differences-from-c-python.md#recursion
