### ISSUE TITLE
System.NullReferenceException when setting new attribute

### ISSUE THREAD

**Issue by ptomin** [IronLanguages/ironpython3#1235]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

### Description

`IronPython` throws `NullReferenceException` when setting new attribute if `__slots__` is defined.

### Steps to Reproduce
```
    var engine = IronPython.Hosting.Python.CreateEngine();
    var script = @"
class Test:
    __slots__ = 'attr'

    def __setattr__(self, name, value):
        super().__setattr__(name, value)

Test().undefined_attr = 0
";
    engine.Execute(script);
```

**Expected behavior:**
`AttributeError: 'Test' object has no attribute 'undefined_attr'`

**Actual behavior:**
`System.NullReferenceException: "Object reference not set to an instance of an object."`

### Versions

3.4.0-alpha

**Comment by slozier** [comment]
Thanks for the report!
