### ISSUE TITLE
SystemError: The module was expected to contain an assembly manifest. (Exception from HRESULT: 0x80131018)

### ISSUE THREAD

**Issue by phamt8611** [IronLanguages/ironpython3#1242]
`import clr, sys`
`sys.path.append('E:\AutoIt3\AutoItX\AutoItX3.dll')`
`#sys.path[5] = E:\AutoIt3\AutoItX\AutoItX3.dll`
`clr.AddReferenceToFileAndPath(sys.path[5])`

SystemError: The module was expected to contain an assembly manifest. (Exception from HRESULT: 0x80131018)

**Comment by slozier** [comment]
Is this a .NET DLL?

**Comment by phamt8611** [comment]
> Đây có phải là .NET DLL không?

I want to add the dll of this: https://www.autoitscript.com

**Comment by slozier** [comment]
`AutoItX3.dll` is not a .NET DLL. Use `AutoItX3.Assembly.dll` instead.

**Comment by phamt8611** [comment]
> `AutoItX3.dll` is not a .NET DLL. Use `AutoItX3.Assembly.dll` instead.

I succeeded
Thank you!!!
