### ISSUE TITLE
Missing execute permission for files in debian package.

### ISSUE THREAD

**Issue by domdfcoding** [IronLanguages/ironpython3#1266]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

After installing the `.deb` package from [the releases page](https://github.com/IronLanguages/ironpython3/releases/tag/v3.4.0-alpha1), attempting to run `ipy` results in the following:

```console
$ ipy
bash: /usr/bin/ipy: Permission denied
```

Looking at the permissions on the file, it is missing the execute (`x`) permission for everybody:

```console
$ ls -l /usr/bin/ipy
-rw-r--r-- 1 root root 60 Apr 21 04:11 /usr/bin/ipy
```

Compare this with the Python 3.8 executable, where everyone has the execute permission:

```console
$ ls -l /usr/bin/python3.8
-rwxr-xr-x 1 root root 5490352 Jun  2 11:49 /usr/bin/python3.8
```

It's the same for `ipy3` and `ipy3.4`

### Steps to Reproduce

1. Download the `.deb` package from https://github.com/IronLanguages/ironpython3/releases/tag/v3.4.0-alpha1
2. Install it (`sudo dpkg -i ironpython_3.4.0-alpha1.deb && sudo apt -f install`)
3. Run the `ipy` command.

**Expected behavior:** 

The IronPython interpreter starts.

**Actual behavior:** 

```console
bash: /usr/bin/ipy: Permission denied
```

### Versions

You can get this information from executing `ipy -V`.

**Comment by slozier** [comment]
Thanks for the report!
