### ISSUE TITLE
How to import Python opencv？

### ISSUE THREAD

**Issue by botao1995** [IronLanguages/ironpython3#1268]

**Comment by slozier** [comment]
Unfortunately the `opencv-python` module seems to depend on numpy so that won't work. You could try using one of the .NET wrappers (for example EmguCV or OpenCvSharp)...

**Comment by botao1995** [comment]
> Unfortunately the `opencv-python` module seems to depend on numpy so that won't work. You could try using one of the .NET wrappers (for example EmguCV or OpenCvSharp)...

If so, I think the ironpython3 route runs in the opposite direction. The correct way is to translate it directly into a python parser, which can directly embed Python code, not a string.
