### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by wuyu8512** [IronLanguages/ironpython3#1278]
`print('\u2022')`
![image](https://user-images.githubusercontent.com/33444499/129928823-c3260a6a-37c4-4bb2-8202-b45bb551c51b.png)

The test environment is a Chinese system. Is there any way to solve this problem ?
or can change `TextIOWrapper.Encoding` to `utf-8` ?

**Comment by slozier** [comment]
Maybe you can try:
```py
import System
System.Console.OutputEncoding = System.Text.Encoding.UTF8;
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, "utf-8", "w")
print('\u2022')
```
I'm not sure how well it works...

**Comment by BCSharp** [comment]
This is intended behaviour (CPython does the same). The solution provided by @slozier works OK on my system, though I'd recommend changing
```python
System.Console.OutputEncoding = System.Text.Encoding.UTF8;
```
to
```python
System.Console.OutputEncoding = System.Text.Encoding.GetEncoding(65001)
```
The difference is that the former has a non-empty preamble (3 bytes of byte-order-mark), while the latter doesn't, which is what you want for console output. It should work OK in both cases, but I am not sure if there are some code paths that would print the preamble anyway.

Alternatively, if this still does not help, you may try to change the console code page before launching `ipy` in that console. For `cmd.exe`:
```
chcp 65001
```
For Powershell:
```powershell
chcp 65001
[Console]::OutputEncoding = [Text.Encoding]::GetEncoding(65001)
```

**Comment by wuyu8512** [comment]
@BCSharp @slozier
Thank you for your answers, it's resolve my issue
