### ISSUE TITLE
Remove support for .NET Core 2.1

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#1287]
End of support by Microsoft for .NET Core 2.1 was August 21, 2021 so I can't think of a good reason to keep a specific .NET Core 2.1 build. If someone still needs to use it then the .NET Standard 2.0 DLL should do the trick?

**Comment by BCSharp** [comment]
Good riddance. I think there may be some workarounds for bugs in Core 2.1 left behind…

**Comment by slozier** [comment]
Yes, there's definitely some code left behind. I've left the 2.1 test suite going (for now) so that something's testing the .NET Standard 2.0 assemblies. But I'm open to eliminating some of the workarounds.
