### ISSUE TITLE
https://github.com/IronLanguages/ironpython3/blob/master/Documentation/building.md is obsolete

### ISSUE THREAD

**Issue by Narick9** [IronLanguages/ironpython3#1306]
https://github.com/IronLanguages/ironpython3/blob/master/Documentation/building.md
It says:
> To build IronPython3 you will need the .NET SDK (minimum v5.0.100).

Now build script requires at least .NET 6.0 SDK
![image_2021-11-19_230824](https://user-images.githubusercontent.com/58558002/142685352-fb6e3f10-86df-4b0b-964d-850332d148cd.png)

**Comment by slozier** [comment]
Thanks for the report. .NET 6 targets were added recently and I missed this requirement. Fixed!
