### ISSUE TITLE
exe genereted by ipyc says "the calling thread must be sta because many ui components require"

### ISSUE THREAD

**Issue by retsyo** [IronLanguages/ironpython3#1310]
I used the following code with latest ironpython2 and ironpython3 release.
no matter `IronPython.2.7.12\net45\ipy.exe  gui_wpf.py` or `IronPython.3.4.0-alpha1\net46\ipy.exe gui_wpf.py` can run without problem. 

Then I use `ipyc` to create exe file with
```
ipyc.exe /embed  /target:exe gui_wpf.py
````

I copy `gui_wpf.exe`, `form.xaml`, `IronPython.2.7.12\lib` to `IronPython.2.7.12\net45\`  
or 
copy `gui_wpf.exe`, `form.xaml`, `IronPython.3.4.0-alpha1\lib` to `IronPython.3.4.0-alpha1\net46\`. 

However when I run `gui_wpf.exe` in the dos prompt, I get
```
gui_wpf.exe
Error occurred: the calling thread must be sta because many ui components require
```

how to fix it? Thanks

the following code is actually `copied` from https://stackoverflow.com/questions/47953638/button-click-event-on-ironpython-wpf
```python
# gui_wpf.py

import clr
import wpf

from System.Windows import Application, Window

class MyWindow(Window):
    def __init__(self):
        self.ui = wpf.LoadComponent(self, 'form.xaml')

    def Button_Click(self, sender, e):
        print('Button has clicked')

if __name__ == '__main__':
    Application().Run(MyWindow())

```
and `form.xaml` is
```xml
<Window 
       xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
       xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" 
       Title="WpfApplication1" Height="300" Width="300"> 
       <Grid>
        <Button x:Name="BUTTON" Content="Button" HorizontalAlignment="Left" Margin="101,82,0,0" VerticalAlignment="Top" Width="75" Click="Button_Click" Background="#FFFF1616"/>
    </Grid>
</Window> 

```

**Comment by slozier** [comment]
You probably need to use `/target:winexe` for a WPF application:
```
ipyc.exe /embed  /target:winexe gui_wpf.py
```

**Comment by retsyo** [comment]
`winexe` works. Thanks

but for the original code, the event prints text in dos windows. If GUI+console window are desired, how can we modify the code to let both `exe` and `py` work?

**Comment by slozier** [comment]
Hmm, I'm not seeing any command-line arguments that would enable this. I guess ipyc would need to be modified to add the STAThread attirbute to the entry point.
