### ISSUE TITLE
The engine loading speed has slowed down

### ISSUE THREAD

**Issue by kyjdp** [IronLanguages/ironpython3#1313]
I'm using ironpython2 engine in PowerShell. It works very well. I'm trying to use ironpython3 engine in these days

I find The engine loads Twice as slow as ironpython 2, Please see the following git pictures, 

How to improve loading speed? need to add some parameters? Any suggestion is welcome. Thank you in advance

My system:  Windows7   64bit    .Net Framwork 4.8    powershell5.1

![Pic](https://user-images.githubusercontent.com/6350504/151744021-61a99333-8eaf-42c7-b564-b4d6a2037c96.gif)

powershell Code:
ipy2.ps1
```
$start = (Get-Date)

$ipy2 = ".\IPY2\NET45\IronPython.dll"
Add-Type -Path $ipy2
$py2 = [ironpython.hosting.python]::CreateEngine()

$py2.Execute("print 'IronPython The engine has been loaded!'") #ipy2

(New-TimeSpan $start).totalseconds
```

ipy3.ps1
```
$start = (Get-Date)

$ipy3= ".\IPY3\NET46\IronPython.dll"
Add-Type -Path $ipy3
$py3 = [ironpython.hosting.python]::CreateEngine()

$py3.Execute("print('IronPython The engine has been loaded!')") #ipy3

(New-TimeSpan $start).totalseconds
```

**Comment by slozier** [comment]
Thanks for the report. I'm pretty sure this is caused by the bootstrapping of `importlib` during engine creation. There's no option to disable this right now but I can look at making one available for the next release.

**Comment by kyjdp** [comment]
> Thanks for the report. I'm pretty sure this is caused by the bootstrapping of `importlib` during engine creation. There's no option to disable this right now but I can look at making one available for the next release.
Thank you for your reply,
Your suggestion is a good idea. Loading the library when necessary can submit the operation efficiency
