### ISSUE TITLE
Python is open-source

### ISSUE THREAD

**Issue by Advik-B** [IronLanguages/ironpython3#1321]
###  Prerequisites

in [readme.md](./readme.md):
```
IronPython is an open-source implementation of the Python programming language
```

The thing is... [python IS open-source](https://github.com/python/cpython)

* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `ipy -V`.

**Comment by slozier** [comment]
I don't see the problem...

**Comment by Advik-B** [comment]
in the readme file

**Comment by BCSharp** [comment]
@Advik-B Your quote is out of context. The full sentence is: _IronPython is an open-source implementation of the Python programming language **which is tightly integrated with .NET.**_ (emphasis mine). 

Your link points to CPython, another open-source implementation of the Python programming language, written in C and not related to .NET in any way. I see no problem in our documentation.

**Comment by Advik-B** [comment]
![image](https://user-images.githubusercontent.com/86160411/154801376-bbaa989d-5637-4b2d-818f-3d49834345d0.png)
@BCSharp look... no programming lang is built JUST FOR .NET ( other than C#, F#, etc) and at first glance... anyone will think python is open-source

source of the image: https://www.educba.com/is-python-open-source/
