### ISSUE TITLE
Build the convetional way with visual studio does not work.

### ISSUE THREAD

**Issue by BVPlaten** [IronLanguages/ironpython3#1371]
### Description

I have tried to build ipy3 and got a lot of CS0234	Errors. I think this should be possible in the way that is explained in the documentation. Or the doc is changed to use the PowerShell. 

### Steps to Reproduce

1. Open the sln-file in Microsoft Visual Studio Community 2022 (64-Bit) - Preview Version 17.2.0 Preview 1.0
2. Hit F6
3. Then i got the error [Compiler Error CS0234](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0234?f1url=%3FappId%3Droslyn%26k%3Dk(CS0234))

**Expected behavior:**
The project should be build when hitting F6 (my opinion)

**Actual behavior:** 
You have to use the power-shell script to build the project.

### Versions
Microsoft Visual Studio Community 2022 (64-Bit) - Preview Version 17.2.0 Preview 1.0
IronPython 3.4.0 3.4.0.0 on .NET 3.1.23

Thanks much for your great work and kind regards 
Bernd

**Comment by simplicbe** [comment]
@BVPlaten do you have a code-line to this error?

**Comment by BVPlaten** [comment]
Hi,

yes. But I have the errors only in German. Sorry:

Fehler	CS0103	Der Name "ConversionResultKind" ist im aktuellen Kontext nicht vorhanden.	IronPython (net46), IronPython (net5.0), IronPython (net6.0), IronPython (netcoreapp3.1), IronPython (netstandard2.0)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPython\Compiler\Ast\AndExpression.cs	42	Aktiv
Fehler	CS0234	Der Typ- oder Namespacename "Actions" ist im Namespace "Microsoft.Scripting" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.)	IronPython (net46), IronPython (net5.0), IronPython (net6.0), IronPython (netcoreapp3.1), IronPython (netstandard2.0)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPython\Compiler\Ast\AndExpression.cs	8	Aktiv
Fehler	CS0234	Der Typ- oder Namespacename "Utils" ist im Namespace "Microsoft.Scripting" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.)	IronPython (net46), IronPython (net5.0), IronPython (net6.0), IronPython (netcoreapp3.1), IronPython (netstandard2.0)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPython\Compiler\Ast\AndExpression.cs	9	Aktiv
Fehler	CS0234	Der Typ- oder Namespacename "Ast" ist im Namespace "Microsoft.Scripting" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.)	IronPython (net46), IronPython (net5.0), IronPython (net6.0), IronPython (netcoreapp3.1), IronPython (netstandard2.0)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPython\Compiler\Ast\AndExpression.cs	13	Aktiv
Fehler	CS0006	Metadatendatei "C:\Users\b_vie\source\repos\ironpython3\bin\Debug\net46\IronPython.dll" wurde nicht gefunden.	IronPythonConsole32 (net46)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPythonConsole32\CSC	1	Aktiv
Fehler	CS0006	Metadatendatei "C:\Users\b_vie\source\repos\ironpython3\Src\DLR\bin\Debug\net45\Microsoft.Dynamic.dll" wurde nicht gefunden.	IronPythonConsole32 (net46)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPythonConsole32\CSC	1	Aktiv
Fehler	CS0006	Metadatendatei "C:\Users\b_vie\source\repos\ironpython3\Src\DLR\bin\Debug\net45\Microsoft.Scripting.dll" wurde nicht gefunden.	IronPythonConsole32 (net46)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPythonConsole32\CSC	1	Aktiv
Fehler	CS0006	Metadatendatei "C:\Users\b_vie\source\repos\ironpython3\Src\DLR\bin\Debug\net45\Microsoft.Scripting.Metadata.dll" wurde nicht gefunden.	IronPythonConsole32 (net46)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPythonConsole32\CSC	1	Aktiv
Fehler	CS0103	Der Name "ContractUtils" ist im aktuellen Kontext nicht vorhanden.	IronPython (net46), IronPython (net5.0), IronPython (net6.0), IronPython (netcoreapp3.1), IronPython (netstandard2.0)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPython\Compiler\Ast\AndExpression.cs	17	Aktiv
Fehler	CS0103	Der Name "ContractUtils" ist im aktuellen Kontext nicht vorhanden.	IronPython (net46), IronPython (net5.0), IronPython (net6.0), IronPython (netcoreapp3.1), IronPython (netstandard2.0)	C:\Users\b_vie\source\repos\ironpython3\Src\IronPython\Compiler\Ast\AndExpression.cs	18	Aktiv

**Comment by BVPlaten** [comment]
<TargetFrameworks>net46;netcoreapp3.1;netstandard2.0;net5.0;net6.0</TargetFrameworks> 

I hope that is what you mean...?!

**Comment by slozier** [comment]
How did you acquire the source? It sounds like you might be missing the source for the DLR (though not sure since I don't understand German :smile:). If it's via git you need to pull the submodules as well:
```
git submodule update --init
```

**Comment by BVPlaten** [comment]
Ah okay. Thanks. I was not aware of that. I will try that's.

So I think the docs should be extended with this.

Many thanks for the hint and have a nice evening.





slozier ***@***.***> schrieb am Di., 22. März 2022, 17:16:

**Comment by BVPlaten** [comment]
After the sub-module update it works now. Thank you very much for the hint.

I was not able to build the Version for the .net framework 4.5. You cannot download the Development Pack. On the download-page you can read : 

"This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as [.NET Framework 4.8](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48). See our [support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-framework) for more details."

I don't think that i ever will need that version. Just want to inform about that issue. 

If you like i will update the documentation with the info of the sub-modules.

Have a nice day and kind regards.

**Comment by slozier** [comment]
> I was not able to build the Version for the .net framework 4.5. You cannot download the Development Pack. On the download-page you can read :
> 
> "This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as [.NET Framework 4.8](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48). See our [support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-framework) for more details."

I also hit this issue recently and had to resort to trickery to get things to compile. I was considering bumping the DLR to .NET Framework 4.6 because of this issue (and I assume ironpython2 will need to follow) however .NET Framework 4.5.2, 4.6 and 4.6.1 are nearing end-of-support as well (April 26, 2022) so I'm holding out to see how things play out.

> If you like i will update the documentation with the info of the sub-modules.

If you can make things clearer that would definitely be helpful.
