### ISSUE TITLE
.NET property not accessible in derived classes

### ISSUE THREAD

**Issue by Cyril-Pop** [IronLanguages/ironpython3#1375]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [x] Are you running the latest version?
* [x] Did you perform a cursory search?

### Description

.NET property is not accessible in derived classes where only the setter or the getter has been overridden
a workaround is to use the unbound base class instance method syntax (Ipy2 or Ipy3)

### Steps to Reproduce

C# lib
```
using System;
using System.Collections.Generic;

namespace TestGetter
{
    public class BaseClass
    {
        protected string name = "noname";

        public virtual string Name 
        {
        	get { return name; }
        	set {name = value; }
        }
    }

    public class DerivedClass : BaseClass
    {
        public override string Name 
        	{ 
        	set { base.Name = value.ToUpper();}
        	}
    }
}
```
Python code
```
import clr
import sys
import System
print(sys.implementation) 
print(sys.version)
sys.path.append(r'C:\Users\****l\Documents\SharpDevelop Projects\TestGetter\TestGetter\bin\Debug')
clr.AddReference("TestGetter")
from TestGetter import BaseClass, DerivedClass

d = DerivedClass()
b = BaseClass()

b.Name = 'BaseClass Name'
d.Name = 'DerivedClass Name'
print("#" * 40)
print(b.Name)   # ok
print("#" * 40)
try:
	print(d.Name)   # TypeError: property cannot be read
except:
	import traceback
	print(traceback.format_exc())
print("#" * 40)
try:
	print(BaseClass.Name.GetValue(d))  # workaround ok
except:
	import traceback
	print(traceback.format_exc())
```
Result
![image](https://user-images.githubusercontent.com/53660624/159962451-35c18c24-da45-426e-a883-4a8562702341.png)

**Comment by slozier** [comment]
Thanks for the report, I was able to reproduce the issue.
