### ISSUE TITLE
struct.pack does not respect __index__ operator

### ISSUE THREAD

**Issue by BCSharp** [IronLanguages/ironpython3#1381]
Packing using `struct` fails if the argument to be packed is not convertible to the desired type using `Converter.TryConvertToXXX`. If the argument defines `__index__`, CPython uses this operator to obtain an integer value.

This affect all data getter helpers for integer types in `_struct.cs`, which do not call `PythonOps.TryToIndex`.

```python
import struct

class Index:
    def __index__(self):
        return 1

assert struct.pack("i", Index()), b'\x01\x00\x00\x00'
```

**Comment by slozier** [comment]
Indeed, and it's also accepting objects with `__int__` when it shouldn't:
```
import struct

class NotInt:
    def __int__(self):
        return 1

try:
    struct.pack("<i", NotInt())
    assert False
except struct.error:
    pass
```
