### ISSUE TITLE
Uninstalling the MSI package leaves keys in Registry behind

### ISSUE THREAD

**Issue by BCSharp** [IronLanguages/ironpython3#1434]
### Description

Since #1187 ([PEP 514](https://peps.python.org/pep-0514/)), the MSI installer adds key `IronPython` under `HKLM:\SOFTWARE\Python`. This key has two subkeys: `3.2` and `3.4-32`. However, upon uninstalling the package, only the `3.4` subkey is removed and subkey `3.4-32` remains.

### Expected behavior

Both subkeys are removed on uninstall. Their parent key `IronPython` may stay, if that makes implementation easy, but for a nice zero-footprint installation, it should be removed too, if there are no other subkeys present.

### Versions

```
IronPython 3.4.0b1 (3.4.0.0010)
[.NETFramework,Version=v4.6 on .NET Framework 4.8.4470.0 (64-bit)]
```

**Comment by slozier** [comment]
Hmm, not able to reproduce this. When I uninstall everything is cleaned up for me?

**Comment by BCSharp** [comment]
Can't explain it. It was reproducible every time I tried. Now it is not reproducible every time I try. The only significant thing that happened in between is that I installed and uninstalled ironpython3 using a local feed for Chocolatey. I had to scroll back my console to believe I wasn't imagining it.
