### ISSUE TITLE
Bump up to .NET Framework 4.6.2

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#1481]
.NET Framework 4.6 has gone out of support on April 26, 2022. I propose we bump up to target .NET Framework 4.6.2. The question is should we do this before or after the 3.4.0-final release. I'm also planning on bumping the DLR to at least 4.5.2 (since the dev pack for 4.5 is no longer available in VS2022 - see https://github.com/IronLanguages/ironpython3/issues/1371).

**Comment by BCSharp** [comment]
I don't have a strong opinion on this, but if you have time, bumping it before 3.4-final has my slight preference. It decreases the chance of having to bump it up again when some third party lib needs to be included (like SQLite — not that I advocate for any such move for 3.4, but just in case.)
