### ISSUE TITLE
System.IO.File not available

### ISSUE THREAD

**Issue by chaojian-zhang** [IronLanguages/ironpython3#1498]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

Spawn an engine instance and try your best to do this (using python):

`System.IO.File.ReadAllText("Path\To\Some\File")`

The result is you can't since there is no way to access the **File** class.

### Steps to Reproduce

1. In C#, create IronPython engine instance
2. Start evaluation by adding all necessary namespace and clr reference (e.g. "System.Runtime")
3. Try to access System.IO.File class

**Actual behavior:** Both System.IO.File and System.IO.Directory are not accessible - however, System.IO.Path is accessible.

**Expected behavior:** Expect all typical System.IO classes are accessible once System.Runtime.dll is added as reference.

![IronPython](https://user-images.githubusercontent.com/7077098/175662413-8862ef4b-5fa7-4ac2-a725-c47d80b1a1de.gif)

### Versions

You can get this information from executing `ipy -V` (Comment: Where do you execute this?).

I am using Nuget: 3.4.0-beta1

**Comment by slozier** [comment]
What version of .NET are you using? On .NET 5 `System.IO.File` is in the `System.IO.FileSystem` assembly:
```py
import clr
clr.AddReference('System.IO.FileSystem')
import System
print(System.IO.Path)
print(System.IO.File)
```

**Comment by BCSharp** [comment]
Related report: #1388

**Comment by chaojian-zhang** [comment]
> What version of .NET are you using? On .NET 5 `System.IO.File` is in the `System.IO.FileSystem` assembly:
> 
> ```python
> import clr
> clr.AddReference('System.IO.FileSystem')
> import System
> print(System.IO.Path)
> print(System.IO.File)
> ```

Yes I was using .net 5.

In that case it's probably my fault. I will try it again on Monday and close this issue if it works.

**Comment by chaojian-zhang** [comment]
Can confirm, per [this doc page](https://docs.microsoft.com/en-us/dotnet/api/system.io.file?view=net-5.0);
Do note that in [.Net 6](https://docs.microsoft.com/en-us/dotnet/api/system.io.file?view=net-6.0) it's in System.Runtime.dll

Closing.
