### ISSUE TITLE
Use index instead of TryConvertToInt64 in socket.__init__

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#1509]
In the 3.6 branch, `socket.__init__` uses `Converter.TryConvertToInt64` on the `fileno`. This is incorrect and probably should be something like `TryToIndex`.

See comment by @BCSharp https://github.com/IronLanguages/ironpython3/pull/1507#issue-1306616504 for details.

**Comment by Grub4K** [comment]
The problem with `TryToIndex` is it uses `TryGetInt` internally. While the function can be duplicated, its the same except with `if (bi.AsInt64(out value)) return true;`. Same for the `TryConvertToIndex64` with `TryGetInt` => `TryGetInt64`.

Otherwise the code could be as simple as:
```cs
long l = Converter.ConvertToIndex64(fileno, throwOverflowError: true);
// Windows reserves only INVALID_SOCKET (-1) as an invalid handle
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? l == -1 : l < 0) {
    throw PythonOps.ValueError("File descriptor cannot be negative");
}
socket = HandleToSocket(l);
if (socket is null) {
    throw PythonOps.OSError("Bad file descriptor");
}
```

**Comment by slozier** [comment]
Thanks for the feedback! I guess I should have been clearer. I believe my intent was to say that we should probably be using `PythonOps.TryToIndex` and not one of the `Converter` methods although I didn't verify that this is indeed the desired logic.

**Comment by Grub4K** [comment]
Oh, that's right. I focused on the `Converter` method instead, but the `PythonOps` one does exactly the same and is more flexible. The working code is
```cs
if (!PythonOps.TryToIndex(fileno, out object? handleObj)) {
    throw PythonOps.TypeErrorForUnIndexableObject(fileno);
}
long handle = Converter.ConvertToInt64(handleObj);
// Windows reserves only INVALID_SOCKET (~0) as an invalid handle
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? handle == ~0 : handle < 0) {
    throw PythonOps.ValueError("negative file descriptor");
}
socket = HandleToSocket(handle);
if (socket is null) {
    throw PythonOps.OSError(RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
        ? PythonErrorNumber.WSAENOTSOCK : PythonErrorNumber.EBADF,
        "Bad file descriptor");
}
```
It mirrors what py3.10 does so unlike py3.6 it supports `__index__`, which should be fine since it's an extension?

While the current CPython tests do check the `fileno` parameter, ipy is not at that state yet (Upstream PR: python/cpython#10917). Should we just use the newer tests for this? The above implementation passes my backport of said tests as I now set the expected `OSError.errno`.

I can open a PR but have no concrete idea on where to implement the according tests correctly. If there is more I can do please let me know.

**Comment by slozier** [comment]
> It mirrors what py3.10 does so unlike py3.6 it supports `__index__`, which should be fine since it's an extension?

Yep that's fine, I've been opting the the 3.10 behaviour in newer code.

> I can open a PR but have no concrete idea on where to implement the according tests correctly. If there is more I can do please let me know.

Sure, if you can do a PR that would be great! I'm thinking the backport to `Src/StdLib/Lib/test/test_socket.py` is fine since it avoids potential duplicated tests in the future. Probably worth having a comment like: `ironpython: backported from 3.10` alongside the test. Note that in order for the tests to actually run they will also need to be listed in `Tests/test_socket_stdlib.py`.
