### ISSUE TITLE
Upgrade section about integers in differences from CPython

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#1572]
https://github.com/IronLanguages/ironpython3/blob/master/Documentation/differences-from-c-python.md#integers

The document still talks about `long` which is no longer applicable. I think the whole section about integers could be dropped since for all intents and purposes we have a single type within the Python realm. @BCSharp Any thoughts?

**Comment by BCSharp** [comment]
Indeed, this whole section can go now, I think. I have re-read the section on `int`/`long` from _upgrading-from-ipy2.md_ and all that stuff is only relevant for interop with .NET. As long as the user stays in pure Python, I see no differences between IronPython 3 and CPython 3.
