### ISSUE TITLE
netstandard2.0 missing dependencies in zip package

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#1584]
The netstandard2.0 folder in the zip package appears to be missing its dependencies. For example there's no Mono.Unix.dll (even though the runtimes folder is there). The three options that come to mind are:
1. Leave it as-is but exclude the `runtimes` folder.
2. Try to include all the required DLLs.
3. Exclude netstandard2.0 from the zip package and tell people to use the NuGet package instead if they want to target .NET Standard.

I am currently leaning towards option 3. @BCSharp I'm not sure if you have a preference.

**Comment by BCSharp** [comment]
I don't have a preference, but I do have a sort of anti-preference for option 1. So option 3 is fine with me.
