### ISSUE TITLE
IronPython dll files and DLR dll files are not installed in GAC

### ISSUE THREAD

**Issue by scott-xu** [IronLanguages/ironpython3#1592]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

When install IronPython 3.4.0 beta 1, the dll files are not installed to GAC

**Expected behavior:** IronPython dll files and DLR files should be installed to GAC, just like IronPython 2.7 installation behavior.

**Actual behavior:** All of the dll files are not installed to GAC

### Versions

3.4.0 beta1

**Comment by scott-xu** [comment]
FYI. The GAC feature is missing, compared with IronPython2.
https://github.com/IronLanguages/ironpython2/blob/master/Package/msi/Product.wxs#L87-L106
https://github.com/IronLanguages/ironpython3/blob/master/Package/msi/Product.wxs#L81-L91

**Comment by slozier** [comment]
Thanks for the report. The feature was removed because installing to the GAC is not something we want to support.

**Comment by scott-xu** [comment]
May I know the reason why dropping the GAC support?

**Comment by slozier** [comment]
The main reason for dropping the GAC was that I did not feel comfortable adding the System.Memory related assemblies to the GAC.
