### ISSUE TITLE
Recursively adding handler in log.addHandler() crashes ironpython

### ISSUE THREAD

**Issue by xiaxinmeng** [IronLanguages/ironpython3#1607]
In ironpython, if we add a log object as a handler recursively, ironpython crashes when it prints log messages. 

test.py:

```
import logging
log = logging.getLogger('logtest')
log.addHandler(log)
log.warning('Works')

```

Error message:
```
>>'ironpython/ironpython3/bin/Debug/net6.0/ipy' test.py
.....
ing.ScriptEngine, Microsoft.Scripting.Hosting.Shell.IConsole, Microsoft.Scripting.Hosting.Shell.ConsoleOptions)
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.RunCommandLine()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.ExecuteInternal()
   at PythonConsoleHost.ExecuteInternal()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Execute()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Run(System.String[])
   at PythonConsoleHost.Main(System.String[])
Aborted (core dumped)
```

Behaviors on CPython 3.9.1(expected):
RecursionError: maximum recursion depth exceeded

System info:
ironpython3-debug(main branch):IronPython 3.4.0b1 DEBUG (3.4.0.0010)[.NETCoreApp,Version=v6.0 on .NET 6.0.11 (64-bit)] on linux
operating system: Ubuntu 18.04.6 LTS

**Comment by slozier** [comment]
Recursion checks are off by default in IronPython, see the Recursion section in [Differences from CPython](https://github.com/IronLanguages/ironpython3/blob/master/Documentation/differences-from-c-python.md#recursion). You need to run with the `-X MaxRecursion=100` argument to get the `RecursionError`.
