### ISSUE TITLE
input() returning "LookupError: unknown encoding: codepage___0" in IronPython 3.4 on Windows 11

### ISSUE THREAD

**Issue by john-tenney-home** [IronLanguages/ironpython3#1625]
### Description

The input() function returns "LookupError: unknown encoding: codepage___0" in IronPython 3.4 on Windows 11.
 
### Steps to Reproduce
We initialize our engine simply:
                pyEngine = CreatePythonEngine(options);
                pyEngine.Runtime.IO.SetInput(stream, Encoding.UTF8);
                pyEngine.Runtime.IO.SetOutput(stream, Encoding.UTF8);
                pyEngine.Runtime.IO.SetErrorOutput(stream, Encoding.UTF8);
And we run like:
     compiledCode.Execute(Scopes[0]);

**Expected behavior:** 
This is how our "raw_input" version looks in 2.7.12.1000
```
>>> a = raw_input("Input Text: ")
﻿Input Text: Hello, world
>>> print(a)
Hello, world
>>> 
```
**Actual behavior:**
This is how the "input" version looks in 3.4.0.1000:
```
>>> a = input("Input Text: ")
Input Text: Traceback (most recent call last):
LookupError: unknown encoding: codepage___0
>>> 
```

### Versions

Running Windows 11 and IronPython 3.4.0.1000

**Comment by slozier** [comment]
Hmm, I'm guessing it's something similar to https://github.com/IronLanguages/ironpython3/issues/961. Although that issue is "resolved" it looks like the encoding on stdin's TextIOWrapper is not updated so that could be causing issues...

You could try something like this as a workaround:
```cs
var runtime = Python.CreateRuntime(options);
runtime .IO.SetInput(stream, Encoding.UTF8);
runtime .IO.SetOutput(stream, Encoding.UTF8);
runtime .IO.SetErrorOutput(stream, Encoding.UTF8);
pyEngine = Python.GetEngine(runtime);
```

**Comment by john-tenney-home** [comment]
Yes, this resolves the issue! Many thanks for the prompt response. I'll leave this open; feel free to close if you think this doesn't warrant any change, but it might cause confusion to others upgrading from 2.7, where the streams can be set after engine creation.

**Comment by eugenelepekhin** [comment]
Hmm, for me it now returns:
LookupException: unknown encoding: utf_8

**Comment by chuongmep** [comment]
Hi, any solution for this so far ?
