### ISSUE TITLE
RegEx sub() with groups fails on empty values

### ISSUE THREAD

**Issue by wizglins** [IronLanguages/ironpython3#1654]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted in [Discussions](https://github.com/IronLanguages/ironpython3/discussions/categories/q-a) or to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

### Description

This code running in python 3.8 would be expected to work:

```
import re

txts = ";[SysSocket]"
txte = ";Adapter.0.EnableSetIpAndMask=1"


ps = r'^(\s*)(?P<S_commenter>[#;]?)(\s*.*[ \t]*)$'
pe = r'^(\s*)(?P<E_commenter>[#;]?)(\s*)(?P<E_key>.+?)([ \t]*=[ \t]*)(?P<E_value>[^#;]*)(\s*.*[ \t]*)$'

s_cmt = ''
e_cmt = ''

key = 'Adapter.0.EnableSetIpAndMask'
value = '1'

exprs = r'\g<1>{cmt}\g<3>'.format(cmt=s_cmt)
expre = r'\g<1>{cmt}\g<3>{key}\g<5>{val}\g<7>'.format(cmt=e_cmt, key=key, val=value)

#Return a match at every white-space character:

x = re.findall(ps, txts)
y = re.sub(ps,exprs, txts)
print(x)
print(y)
print(' ')

x = re.findall(pe, txte)
y = re.sub(pe,expre, txte)

print(x)
print(y)
```

It is about removing (i.e. replacing with empty string) certain characters from a default input string within a ConfigFile.cfg

### Steps to Reproduce

1. Check in https://www.w3schools.com/python/trypython.asp?filename=demo_default
2. Repeat in IronPython

**Expected behavior:** [What you expected to happen]

Output:
```
[('', ';', '[SysSocket]')]
[SysSocket]
 
[('', ';', '', 'Adapter.0.EnableSetIpAndMask', '=', '1', '')]
Adapter.0.EnableSetIpAndMask=1
```

**Actual behavior:** [What actually happened]
Output:

`IndexError: unknown group reference`

### Versions

Found on ipy version 2.7.x, but actually no difference in code is seen in ipy 3.x

**Comment by slozier** [comment]
Thanks for the report!
