### ISSUE TITLE
Memory leak on import (no GC even when out-of-scope)

### ISSUE THREAD

**Issue by D-RX** [IronLanguages/ironpython3#1658]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted in [Discussions](https://github.com/IronLanguages/ironpython3/discussions/categories/q-a) or to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [Yes; latest release 3.4.0] Are you running the latest version?
* [I think so] Are you reporting to the correct repository?
* [Yes] Did you perform a cursory search?

### Description

Using IronPython 3.4.0 in a .NET Framework 4.6.2 project (x86 32-bit), a ScriptEngine, ScriptScope, and ScriptSource created in a new thread and are used to execute a CompiledCode object (also created in that thread).  When libraries or modules are imported via import, the memory used is not released when the thread terminates and garbage collection (GC) is run.  Starting a new thread with the same or different Python source that also imports will eventually lead to a System.OutOfMemoryException being thrown due to GC apparently not freeing the loaded modules or libraries.

Note: variables assigned during a script in this same situation will be GC'd; e.g.,
```
a = []
for n in range(0,52428800):
 a.append(n)
```
In this case, the memory used will be freed at some point after the thread terminates when GC runs, and no OutOfMemoryException is thrown.

### Steps to Reproduce

1. Create a Python script that imports (best if large) libraries or modules.
2. Create a thread via System.Threading that creates a ScriptEngine, ScriptScope (using the script made in 1. as statements), and ScriptSource that are executed via CompiledCode when the thread is run.
3. Start the thread and wait for it to finish and terminate.
4. Start the thread again (and optionally, observe memory usage and note GC events).
5. Repeat 4. until the System.OutOfMemoryException is thrown.

**Expected behavior:** [What you expected to happen]
When the ScriptEngine, ScriptScope, and ScriptSource that are executed via CompiledCode in the thread go out-of-scope when the thread terminates, any memory allocated by those for imported libraries or modules should be eligible for GC.

**Actual behavior:** [What actually happened]
Memory allocated as a result of importing libraries appears to not be eligible for GC even though it goes out-of-scope when the thread terminates.

### Versions

You can get this information from executing `ipy -VV`.
IronPython 3.4.0 (3.4.0.1000)
[.NETFramework,Version=v4.6.2 on .NET Framework 4.8.4515.0 (32-bit)]

**Comment by slozier** [comment]
It looks like it might be related to the importlib bootstrapping mechanism. For example, the following seems to leak memory quite quickly:
```cs
for (var i = 0; i < 10000; i++) {
    var engine = Python.CreateEngine();
    engine.Execute("class Test(object):\r\n    x = [0]*50000000\r\n    def __init__(self):\r\n        pass\r\n\r\nTest()");
    Console.WriteLine(GC.GetTotalMemory(true));
}
```
whereas the same without the importlib does not appear to leak:
```cs
for (var i = 0; i < 10000; i++) {
    var engine = Python.CreateEngine(new Dictionary<string, object> { { "NoImportLib", true } });
    engine.Execute("class Test(object):\r\n    x = [0]*50000000\r\n    def __init__(self):\r\n        pass\r\n\r\nTest()");
    Console.WriteLine(GC.GetTotalMemory(true));
}
```

Maybe related to https://github.com/IronLanguages/ironpython2/issues/83.
