### ISSUE TITLE
__setattr__ not called on Metaclass

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#1661]
### Discussed in https://github.com/IronLanguages/ironpython3/discussions/1660

<div type='discussions-op-text'>

<sup>Originally posted by **zwadar** February 23, 2023</sup>
Hi,
I'm using 3.4.0 and trying to use __setattr__ on a metaclass but it doesn't seem to be called. As far as I can see this should be supported and I don't see any issues reported, so I was wondering if I might be doing something wrong?

    class Test(type):
        def __new__(cls, name, bases, namespace):
            cls = super(Test, cls).__new__(cls, name, bases, namespace)
            return cls        
   
        def __setattr__(cls, attr, value):
            print("Called Set Attr")
            super(Test, self).__setattr__(attr, value)
    
    class TestMeta(object, metaclass=Test):
        aaa = 10
    
    TestMeta.aaa = 80
    print(TestMeta.aaa)

but the printed output is just

   80

Can I somehow overcome it? This is pretty crucial to me.

Thank you</div>

---

Here's a potential test case:
```py
class Test(type):
    def __setattr__(cls, attr, value):
        super().__setattr__("last_attr", (attr, value))
        super().__setattr__(attr, value)

class TestMeta(metaclass=Test):
    aaa = 10

TestMeta.aaa = 80

assert TestMeta.aaa == 80
assert TestMeta.last_attr == ("aaa", 80)
```

**Comment by zwadar** [comment]
fiy I had tried to fix it by changing the line
https://github.com/IronLanguages/ironpython3/blob/master/Src/IronPython/Runtime/Types/PythonType.cs#L1304

to
` ((BuiltinMethodDescriptor)pts).DeclaringType == typeof(PythonType);`

and it actually worked, except it had broke ctypes tests. But I supposes this method is the one that needs fixing.
