### ISSUE TITLE
Field 'None'  in .Net Enumeration is not supported 

### ISSUE THREAD

**Issue by Cyril-Pop** [IronLanguages/ironpython3#1680]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?

### Description

Hi,
Field `None` in .Net Enumeration is not supported, works fine in ipy2

### Steps to Reproduce

```
import clr
import sys
import System

testEnum = System.IO.FileShare.None
```

**Expected behavior:** 

No Error

**Actual behavior:** 

Syntax Error 

![image](https://user-images.githubusercontent.com/53660624/232052361-01c935c6-a41b-437b-a256-44e4181fb2ab.png)

### Versions

ipy 3.4.0

**Comment by slozier** [comment]
`None` is a keyword as part of the Python 3 language spec so you cannot use `.` to access the member. You'll have to use alternate notation, for example `FileShare["None"]`. See [`None` is a keyword](https://github.com/IronLanguages/ironpython3/blob/master/Documentation/upgrading-from-ipy2.md#none-is-a-keyword) in the upgrade documentation.

**Comment by Cyril-Pop** [comment]
Ah ok, I understand, thanks for the feedback.
Congratulations again to the team
