### ISSUE TITLE
Testing the IronPython C# code with LinqPad5 does not print any output

### ISSUE THREAD

**Issue by kyjdp** [IronLanguages/ironpython3#1716]
I tested the code below in LinqPad5 and LinqPad7, but there was no output.
However, using IronPython 2, the code can output normally.

```
static void Main(string[] args)
{
	var pythonEngin = Python.CreateEngine();
	var pythonScripts = pythonEngin.CreateScriptSourceFromString("print('hello world')");
	pythonScripts.Execute();
}
```

![a](https://github.com/IronLanguages/ironpython3/assets/6350504/91c248d4-af66-4217-8d66-744bb14290ff)

**Comment by BCSharp** [comment]
LinqPad redirects `Console.Out`. Redirecting works differently in IronPython 3. See https://github.com/IronLanguages/ironpython3/blob/master/Documentation/upgrading-from-ipy2.md#redirecting-output.
