### ISSUE TITLE
"not a Zip file" - what does it mean?!

### ISSUE THREAD

**Issue by sensboston** [IronLanguages/ironpython3#1775]
It's not a "feature request" but a simple question: I read some articles saying the "IronPhyton is best way to incorporate Python into your C# solution". OK, I followed  some steps (mostly the same) and trying to run Python script obtained from https://github.com/tsurumeso/vocal-remover
But... immediately I got an exception: 
```
Exception thrown: 'IronPython.Runtime.Exceptions.ImportException' in IronPython.Modules.dll
An exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in IronPython.Modules.dll but was not handled in user code
not a Zip file
```
Could anyone tell me what's going on?! What the "Zip file"?! No one zip-file was injured until your software reported that nonsense!

So please be honest: should I junk this "Iron**y**Python" and just run normal Python3 with console redirection? BTW, what is this repo stands for?

**Comment by slozier** [comment]
Congratulations, you just witnessed an exception that was thrown (and then caught). Python includes [`zipimport.zipimporter`](https://docs.python.org/3/library/zipimport.html#zipimport.zipimporter) in its path hooks that throws a "Not a Zip file" `ImportError` when a path is (unsurprisingly) not a zip file...

If you want to use vocal-remover then yes I suggest using normal CPython.

**Comment by sensboston** [comment]
I got rid from all these "python-kind" nuget packages and created a nice console helper C# class, working with the official, standard Python 3. Now everything is working like a charm.
