### ISSUE TITLE
No way to programmatically stop execution

### ISSUE THREAD

**Issue by DJSures** [IronLanguages/ironpython3#1780]
### Prerequisites

* [YES ] Are you running the latest version?
* [ YES] Are you reporting to the correct repository?
* [ YES] Did you perform a cursory search?

### Description

There is no way to stop a script that is being executed from another thread. The script engine has no cancellation token or "cancel" option. The suggestions to use Thread.Abort() is not supported in .NET 8

### Steps to Reproduce

Run a Python script that is a loop, and it runs forever. There is no way to stop the execution engine. Thread.Abort() gives an "unsupported method" exception.

**Expected behavior:**

The ability to stop a script that is running.

**Actual behavior:**

The script runs forever until the application is exited. If the thread is aborted, the exception of "unsupported method" is raised.

### Version Information

.Net 8
NuGet Package: 3.4.1
Windows 10, Linux Ubuntu (x64 & ARM64)

**Comment by slozier** [comment]
There's the [System.Runtime.ControlledExecution](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.controlledexecution) which we might be usable instead of `Thread.Abort` although I haven't had a chance to try it out myself...

**Comment by DJSures** [comment]
> There's the [System.Runtime.ControlledExecution](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.controlledexecution) which we might be usable instead of `Thread.Abort` although I haven't had a chance to try it out myself...

Thanks for the suggestion; however, that is deprecated as well. Do you have another suggestion? Isn't there a place in the IronPython library where we can insert a cancellationtoken to be checked during execution? I don't need it to be a Task or async. That's fine, i just need to somehow cancel the execution of a script from another thread.

![image](https://github.com/IronLanguages/ironpython3/assets/49293683/d268e9d5-e8de-4f76-b896-7f39734d2ac9)

**Comment by Muny** [comment]
FWIW, I check for cancellation inside a Traceback callback (`scriptEngine.SetTrace()`), and raise an exception if so. It probably has somewhat of a performance impact, and it won't immediately cancel things like `sleep()`.

I do wish there was a neater solution.

**Comment by wally96334** [comment]
I am trying to resolve the same problem.

https://github.com/IronLanguages/ironpython3/issues/1779

My approach is to spin off an app domain, then trash the app domain in the event that execution is to be aborted.

**Comment by DJSures** [comment]
> FWIW, I check for cancellation inside a Traceback callback (`scriptEngine.SetTrace()`), and raise an exception if so. It probably has somewhat of a performance impact, and it won't immediately cancel things like `sleep()`.
> 
> I do wish there was a neater solution.

That works flawlessly!! Thank you so much. I was in a bit of a panic - and this is far more elegant than Thread.Abort().

**Comment by DJSures** [comment]
You can create an exception type...

```
public class PythonStopException : Exception {
}
```

Use a cancellation token and source, or a volatile bool. You choose...

```
    volatile bool _cancelRequested = false;
```

Create a delegate for the Trace that checks the cancelation token or volatile bool

```
    private TracebackDelegate OnTraceback(TraceBackFrame frame, string result, object payload) {

      if (_cancelRequested)
        throw new PythonStopException();

      return OnTraceback;
    }
```

in your thread to launch the script, initialize the engine and set the trace to the ontraceback delegate...

```
      _engine = IronPython.Hosting.Python.CreateEngine();
      _engine.SetTrace(OnTraceback);
```

Make sure you catch the exception for the PythonStopException that you made, so it doesn't roll down as an error in your try/catch surrounding the Execute()

**Comment by slozier** [comment]
Glad you found a solution.

> Thanks for the suggestion; however, that is deprecated as well.

Just a side note, it's not really deprecated. It was marked as `Obsolete` right off the bat to discourage its use. See https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0046
