### ISSUE TITLE
PythonType being misidentified as IEnumerable

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#248]
`PythonOps.TryGetEnumerator` is incorrectly succeeding against `PythonType` objects. This causes failures in places which rely on this method to figure out if an object is `IEnumerable`. Here are a few examples:
```Python
# these should fail but don't
zip(object)
filter(None, object)
iter(object)

# this fails but with TypeError: expected Array[Type]
a, *b = object
```

We could probably get away with adding a check for `PythonType` to `TryGetEnumerator` but it would be better to figure out the underlying issue. (Also, I imagine it's possible to craft a type which is iterable?)

**Comment by slide** [comment]
This the same as https://github.com/IronLanguages/main/issues/360?

**Comment by slozier** [comment]
Could be related although the examples appear to be failing properly in ipy2.7.7. Maybe it got fixed?

**Comment by slide** [comment]
Yes, this got fixed in ipy2. I'll merge the fix across.
