### ISSUE TITLE
Implement itertools.filterfalse

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython3#267]
https://docs.python.org/3/library/itertools.html#itertools.filterfalse

From looking at the C Python code, it looks like it is an object a la the dict_keys and other things that have been turned into objects in Python 3

**Comment by rtzoeller** [comment]
I'm interested in tackling this as a first step into IronPython development, but could use a little more guidance as I get started.

The function has clearly been renamed (`ifilterfalse` -> `filterfalse`), which is a trivial change, but there's obviously more to it. Superficially the return type of calling the function appears to match CPython 3.x's (barring the rename, `
<class 'itertools.filterfalse'>`), although looking at the returned objects further there are some clear differences, e.g. the presence of a `__contains__` method on the IronPython version.

Can you elaborate a bit on what exactly the work for filterfalse would look like? I'm slightly confused by the lack of apparent differences in `PythonDictionary.cs/DictionaryKeyView` between IronPython2 and IronPython3, as you called out dict_keys as an example.

**Comment by slozier** [comment]
@rtzoeller Thanks for your interest.

After taking a quick look at this I would say that this is pretty much just a rename from `ifilterfalse` -> `filterfalse`. At the same time I would suggest going through the module and renaming any other method which seems to have dropped the `i` prefix in 3.0.

Like you said, there are a few differences between the methods of the different implementations but I don't think those are differences are necessarily specific to `filterfalse` but more generalized things to fix (for example the unrelated `list_iterator` has the same issues). The differences that I see are:

- `__contains__` in Ipy
- comparison operators in CPy
- `__dir__` in CPy

You can probably safely ignore those differences (though we should probably file issues to capture these differences).
