### ISSUE TITLE
Make fails on Mono 5.0 due to CSC changes.

### ISSUE THREAD

**Issue by ivanbakel** [IronLanguages/ironpython3#310]
Mono 5.0 is now out of beta, and has brought the Roslyn compiler with it, hurray! The changelog can be viewed here: http://www.mono-project.com/docs/about-mono/releases/5.0.0/ .

However, this update seems to be causing some issues with making on Linux, for me at least. The critical error is 

`CSC: error CS8105: Attribute
'System.Reflection.AssemblyKeyNameAttribute' is ignored when public
signing is specified.`

Removing the attribute from two files - where it is set to `""` - eliminates the issue, but I'm not sure the direct solution is the best one. These changes are on my repo: https://github.com/ivanbakel/ironpython3/commit/2b2a0d2de8aec9d3262462ffd1b859d2cd672467

This may be related to the fact that the Roslyn compiler doesn't support full signing if you're not running Windows, but I'm not sure about that.

Addendum: `xbuild` is considered deprecated, and `msbuild` is now available to non-Windows platforms. I would have made a PR for this, but my distro doesn't provide an msbuild package yet.

**Comment by ivanbakel** [comment]
To add something else to this - the comments in both of those AssemblyInfo files suggests that the intention is to use delayed signing, so instead it might be the lack of `[assembly:AssemblyDelaySignAttribute(true)]` that causes the error.

**Comment by slide** [comment]
Mono 5 also has issues running IronPython stuff, I've filed a couple blocking bugs. So, even though Mono 5 is out of beta, it won't work currently for IronPython.

**Comment by slide** [comment]
IronPython3 now builds on Mono
