### ISSUE TITLE
Use TypeCache.Object

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython3#320]
https://github.com/IronLanguages/ironpython3/blob/master/Src/IronPython/Runtime/Operations/PythonOps.cs#L1397

**Comment by slozier** [comment]
Seems like we could use this type of optimization in lots of places. Although GetPythonType already does some caching so is it a big optimization?

**Comment by slide** [comment]
Yeah, it does do some caching. I plan on collecting the places we should do this in this issue.

**Comment by BCSharp** [comment]
Resolved by #1450.
