### ISSUE TITLE
No module named stat

### ISSUE THREAD

**Issue by Gacha-SAMP** [IronLanguages/ironpython3#346]
Hi,

I am currently working on the migration of my program from IronPython 2.7 to IronPython3.
When I tried to "import clr" using Iron Python Interactive, the module "stat" imported in "os.py" is not found.

![image](https://user-images.githubusercontent.com/15857657/32829332-121a736a-c9f2-11e7-9f02-fe059a560a2f.png)

But, I can import the module "stat" in the Python-3.6 console:

![image](https://user-images.githubusercontent.com/15857657/32829398-4ea86cba-c9f2-11e7-8696-4ecffead1cfb.png)

PS: I my folder "Lib", I just have "iptest" and os.py.

**Comment by slide** [comment]
I highly recommend NOT migrating to IronPython3 yet. It is no where near ready. It sounds like you didn't copy the stdlib from Src\StdLib\Lib though if you only have those items in your Lib directory.

**Comment by Gacha-SAMP** [comment]
Yes I have comparated the Lib folder from IronPython2 and IronPython3, then I tried with copying the python file from Src\StdLib\Lib to my Lib folder.

The error seems to be resolved with this but I didn't succeed to use my WPF application (using IPY) with visual studio. Then, I have tried to execute my python script using "ipy.exe" and I have got this error:

Traceback (most recent call last):
  File "C:\Projects\RIEALE\Application\BuildTools\libThera.py-GUI\libThera.py_RI
EALE_GUI.py", line 12, in <module>
ValueError: Attempted relative import in non-package

The line 12 is: from .CommandAction import *
So, I think that he doesn't found my own module.

**Comment by slide** [comment]
Again, IronPython3 is no where ready for use.

**Comment by Gacha-SAMP** [comment]
Ok I will wait for a stable version.

I still managed to get the application running but not using visual studio.
I have just copyied the file from "Src\StdLib\Lib" to my "Lib" folder and I run my application using "ipy.exe PATH OF MY PY FILE"
