### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by jduncalf** [IronLanguages/ironpython3#354]
Hi all, not necessarily an issue. I've successfully built IronPython3 and was hoping to install numpy and scipy. The cmd "ipy -X:Frames -m ensurepip" however results in "Could not import runpy module".

Any help is greatly appreciated. Thanks.

**Comment by slozier** [comment]
It looks like runpy fails to import (at least the first possible failure point) because we haven't implemented `nonlocal`. You could tweak `functools.py` to work without `nonlocal`, but I expect another failure point down the line. IronPython3 just isn't read for use yet.

**Comment by slozier** [comment]
Closing this since `ipy -m ensurepip` was fixed a a while back. There's still an issue with `pip install` for certain modules, but it's tracked at https://github.com/IronLanguages/ironpython3/issues/936.
