### ISSUE TITLE
scipy, numpy

### ISSUE THREAD

**Issue by jduncalf** [IronLanguages/ironpython3#355]
Is it possible yet at IronPython3's stage of development to install/import numpy and scipy?

**Comment by slide** [comment]
No, there are still several syntactical elements that we have not implemented yet. The stdlib uses these, so importing libraries will most likely fail right now.

**Comment by jduncalf** [comment]
Thanks for the speedy reply.

**Comment by guillenmartins** [comment]
Hi guys, (6 years later lol ) But is importing numpy and scipy modules possible now? I tried the steps on the README but it fails because my python code has those modules and it just replies it cannot find them.

**Comment by pierreadcis** [comment]
would be great if numpy and scipy modules can be installed indeed
