### ISSUE TITLE
Update the homepage

### ISSUE THREAD

**Issue by ShalokShalom** [IronLanguages/ironpython3#367]
Hi, I wrote today a pull request at a related project, which should remove their reference to this project, simply because their link provided leads to the current homepage. 

Which means, the people get the impression this project is dead.

At least a status update in form of a simple change of the current versions could work wonders.
Many (potential) devs might be heavily distracted by that, wondering why anyone should use a "2 year in coma" project. : )

**Comment by slide** [comment]
Which homepage are you referring to? ironpython.net shows a release from December of 2016, so a little over a year ago.
