### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Prakash19921206** [IronLanguages/ironpython3#376]
i'm using windows 10 64bit
after cloning the repository, in command prompt i entered 'make'
and got below output

```
process_begin: CreateProcess(NULL, msbuild Build.proj /t:Build /p:Mono=true /p:BuildFlavour=Release "/p:Platform=Any CPU" /verbosity:minimal /nologo, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:7: release] Error 2
```

**Comment by slide** [comment]
You can't use the Makefile on Windows, you need to use make.ps1 under powershell.

**Comment by Prakash19921206** [comment]
sorry for commenting on closed issue,
i cloned a new copy of this repository. then opened powershell as Admin,
navigated to repository folder, and entered ./make.ps1

got a giant list of errors... all were in below format 

> The type or namespace name '<NAME>' does not exist in the namespace '<LIB_NAME>' (are you missing an assembly reference?) 

since the list of error is huge, instead of posting it here, i'm attaching the text file (output from powershell)

am i missing something?
i don't find pre-compiled binaries so somehow i need to figure out to build IronPython3

Thanks & Regards

[IronPython3 Build Error.txt](https://github.com/IronLanguages/ironpython3/files/1757383/IronPython3.Build.Error.txt)

**Comment by slide** [comment]
You need to initialize the submodule for the DLR, so do the equivalent of `git submodule update --init` in the root of the code.
