### ISSUE TITLE
Cannot open project in Visual Studio 2017

### ISSUE THREAD

**Issue by bdonnahue** [IronLanguages/ironpython3#377]
I pulled down the master branch commit a201c0ee58e85aa95104b1056809bf382b406423

Visual Studio shows the following error when I try loading the solution file:

C:\Users\TSchneider1_a\Downloads\ironpython3-master\Src\DLR\Src\Microsoft.Dynamic\Microsoft.Dynamic.csproj : error  : The project file cannot be found.

C:\Users\TSchneider1_a\Downloads\ironpython3-master\Src\DLR\Src\Microsoft.Scripting\Microsoft.Scripting.csproj : error  : The project file cannot be found.

C:\Users\TSchneider1_a\Downloads\ironpython3-master\Src\DLR\Src\Microsoft.Scripting.Metadata\Microsoft.Scripting.Metadata.csproj : error  : The project file cannot be found.

C:\Users\TSchneider1_a\Downloads\ironpython3-master\Src\DLR\Tests\ClrAssembly\ClrAssembly.csproj : error  : The project file cannot be found.

**Comment by slide** [comment]
The DLR is a git submodule, so you need to do the equivalent of `git submodule update --init`

**Comment by bdonnahue** [comment]
Can you please add the required commands to the build instructions? The current instructions do not work.

**Comment by slide** [comment]
Which instructions are you referring to?

**Comment by bdonnahue** [comment]
I apologize. I missed a step where it says to clone recursively. I apologize. Thanks @slide for the quick response.
