### ISSUE TITLE
Load built in modules from embedded C# resource

### ISSUE THREAD

**Issue by byt3bl33d3r** [IronLanguages/ironpython3#382]
Hi,

Was wondering if it's possible to load Python's built in modules from an embedded C# resource as supposed to just appending the path to sys.path? 

Thanks!

**Comment by byt3bl33d3r** [comment]
Just to clarify, by built in modules I mean Python's standard library

**Comment by slide** [comment]
Yes, it is possible to put the stdlib into the assembly as an embedded resource. There is a ResourceMetaPathImporter implementation that can be used. See this SO answer for an example: https://stackoverflow.com/questions/35301682/ironpython-resourcemetapathimporter-failure
