### ISSUE TITLE
How to properly setup CodeContext to directly invoke IO from C#?

### ISSUE THREAD

**Issue by lostmsu** [IronLanguages/ironpython3#387]
I am trying to call IronPython's standard library from C# without dynamic dispatch, but I don' seem to get how to get a proper CodeContext.
```csharp
IronPython.Modules.Builtin.input(__context__, "What is your name?\n")
```

What should I put in place of `__context__`?

I tried to create it like this:
```csharp
var engine = Python.CreateEngine();
var scriptDomainManager = HostingHelpers.GetDomainManager(engine.Runtime);
var scriptScope = engine.CreateModule(nameof(Play));
            
var pythonContext = new PythonContext(scriptDomainManager, options: null);
var moduleContext = new ModuleContext(globals: new PythonDictionary(), DefaultContext.DefaultPythonContext);
var context = new CodeContext(dict: new PythonDictionary(), moduleContext);
````

That properly outputs "What is your name?", but then crashes trying to decode input: unknown encoding: cp437.

I know encodings are supposed to be initialized in Src/StdLib/Lib/encodings/__init__.py, but I can't find how to get it (and all other default modules) loaded properly, so I can't reproduce it in C# program.

[Cross-post on StackOverflow](https://stackoverflow.com/questions/49928724/how-to-properly-setup-codecontext-of-ironpython-to-directly-invoke-io-from-c)

**Comment by slide** [comment]
Please use the mailing list (users@ironpython.groups.io) for questions.

Normally, you would do an import of the encodings library (this is usually done via site.py if you have the stdlib in the path for your IronPython code).
