### ISSUE TITLE
open(..., 'w') ... flush() fails to write data to the file

### ISSUE THREAD

**Issue by lostmsu** [IronLanguages/ironpython3#392]
Repro:
```python3
with open('test.txt', 'w') as test:
  test.write('hi')
  test.flush()
  r = open('test.txt', 'r')
  print(r.read(1))
  r.close()
```
Expected: 'h' printed
Actual: '' printed

This seems to be a regression from IronPython 2.

_Side note_: what surprises me is that in both 3 and 2 `BufferedWriter.flush()` does not call `.flush()` on the underlying `_raw`/`_rawIO`, but somehow it works in IronPython 2. I'd appreciate an explanation. Does IP2 create the underlying stream with buffering off?

**Comment by slide** [comment]
IP3 is not ready for prime time at all, please do not use it.

**Comment by lostmsu** [comment]
@slide , no worries, I am not "using" it in a conventional sense :)

**Comment by slide** [comment]
Ok, that's good :)

**Comment by slozier** [comment]
`open` with ipy3 is actually the `io.open` of ipy2. If you use `io.open` in ipy2 does the same issue occur?

**Comment by lostmsu** [comment]
@slozier looks like it does.

**Comment by slozier** [comment]
It looks like the issue here is that `io.FileIO` should be writing directly to disk and not buffering. If you look at the `flush` method on the CPython `io.FileIO` it's actually the flush method of `_IOBase` (so basically a noop). I think the solution would be to open the `FileStream` with `FileOptions.WriteThrough`.

**Comment by lostmsu** [comment]
Hm, would not it be better to fix `flush`?

**Comment by slozier** [comment]
That would be an incompatibility with CPython. For example:
```Python
import io
b = io.BytesIO()
f = io.BufferedWriter(io.BufferedWriter(b))
f.write(b"a")
f.flush()
assert bytes(b) == b""
```

**Comment by lostmsu** [comment]
@slozier I am not sure what do you mean here. `BufferedWriter` should be calling the underlying IO object's `flush`, so if `flush` is fixed to behave correctly, this would pass.

**Comment by slozier** [comment]
My example is a counter-example to the statement that `BufferedWriter` should call the underlying IO object's `flush`. If it did call `flush`, then the sample above would fail. You can manually flush the `raw` and see the difference:
```Python
import io
b = io.BytesIO()
f = io.BufferedWriter(io.BufferedWriter(b))
f.write(b"a")
f.flush()
assert b.getvalue() == b""
f.raw.flush()
assert b.getvalue() == b"a"
```
