### ISSUE TITLE
Documentation for New Contributors

### ISSUE THREAD

**Issue by brentshermana** [IronLanguages/ironpython3#394]
I'd like to contribute to this project. It seems like documentation is a little sparse, so it's tough to get a sense of what currently works and what doesn't, and what the current goals are.

**Comment by brentshermana** [comment]
How can I set up a build environment? VS2017 prompts me to update the project, but VS2015 has the following project import errors:

`D:\dev\repos\ironpython3\Src\IronPython\IronPython.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\IronPython\IronPython.csproj

D:\dev\repos\ironpython3\Src\IronPython.Modules\IronPython.Modules.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\IronPython.Modules\IronPython.Modules.csproj

D:\dev\repos\ironpython3\Src\IronPython.Wpf\IronPython.Wpf.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\IronPython.Wpf\IronPython.Wpf.csproj

D:\dev\repos\ironpython3\Src\IronPythonConsole\IronPythonConsole.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\IronPythonConsole\IronPythonConsole.csproj

D:\dev\repos\ironpython3\Src\IronPythonTest\IronPythonTest.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\IronPythonTest\IronPythonTest.csproj

D:\dev\repos\ironpython3\Src\IronPythonWindow\IronPythonWindow.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\IronPythonWindow\IronPythonWindow.csproj

D:\dev\repos\ironpython3\Src\IronPython.SQLite\IronPython.SQLite.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\IronPython.SQLite\IronPython.SQLite.csproj

D:\dev\repos\ironpython3\Src\IronPythonCompiler\IronPythonCompiler.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\IronPythonCompiler\IronPythonCompiler.csproj

D:\dev\repos\ironpython3\Src\DLR\Src\Microsoft.Dynamic\Microsoft.Dynamic.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\DLR\Src\Microsoft.Dynamic\Microsoft.Dynamic.csproj

D:\dev\repos\ironpython3\Src\DLR\Src\Microsoft.Scripting\Microsoft.Scripting.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\DLR\Src\Microsoft.Scripting\Microsoft.Scripting.csproj

D:\dev\repos\ironpython3\Src\DLR\Src\Microsoft.Scripting.Metadata\Microsoft.Scripting.Metadata.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\dev\repos\ironpython3\Src\DLR\Src\Microsoft.Scripting.Metadata\Microsoft.Scripting.Metadata.csproj`

**Comment by slozier** [comment]
We have some information about building and requirements in the ipy2 repo (https://github.com/IronLanguages/ironpython2/blob/master/Documentation/building.md). It says that VS2017 15.2 is needed but I'm pretty sure that is incorrect and it should be something like 15.7.

**Comment by brentshermana** [comment]
My 2017 version is 15.7.6, so that must be too far ahead. What version do you run?

**Comment by slozier** [comment]
I'm running 15.8.1 though it was working fine with 15.7. You need to install the ".NET desktop development", the ".NET Core cross-platform development" and (maybe) the "Python development" workloads.

**Comment by slide** [comment]
The Python tools are not required.

**Comment by brentshermana** [comment]
@slozier That worked! Thanks

**Comment by brentshermana** [comment]
I see there a bunch of communication channels (github issues, gitter, stackoverflow, etc.). Is there a preferred channel for handling these kinds of questions?

**Comment by brentshermana** [comment]
I tried running the compiler from my build on a simple hello world program and got an error related to the build .exe/.dlls not being in Path:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'IronPython, Version=3.4.0.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' or one of its dependencies. The system cannot find the file specified.
   at PythonMain.Main()

Is there a setup script to run after building? There are allusions to scripts on [https://github.com/IronLanguages/main/wiki](the wiki), but nothing like what I'm looking for was popping out at me.

**Comment by slide** [comment]
https://gitter.im/IronLanguages/ironpython is a place that is more interactive than here on Github. Can you tell me the steps you used to build and run? Here is what I usually do:

1. Clone source code
2. Open Powershell and cd to the root of the clone
3. Run make.ps1
4. `$env:IRONPYTHONPATH = 'C:\Path\To\Clone\Src\StdLib\Lib'
5. `.\bin\Release\net45\ipy.exe somescript.py`

Is that what you did?

**Comment by brentshermana** [comment]
Your steps work for me. Originally I was trying to work with `ipyc.exe` rather than `ipy.exe`, so my process looked like this:

1) clone
2) build with powershell
3) `<path-to-root>\bin\Debug\net45\ipyc.exe /main:<path-to-hello.py> /target:winexe`
4) `.\hello.exe`

That's where I got the error. After setting the environment variable, I'm not getting that error any more, but I don't get the "hello world!" stdout that I was expecting... the .exe just terminates.

**Comment by slozier** [comment]
Going to close this as there is now https://github.com/IronLanguages/ironpython3/blob/master/CONTRIBUTING.md which provides some information.
