### ISSUE TITLE
.net standard 2 support

### ISSUE THREAD

**Issue by MuhKuh7** [IronLanguages/ironpython3#417]
Will there be a version available for .net standard 2?

**Comment by slide** [comment]
No, there won't be. .net standard 2.0 is missing some features (reflection.emit).

**Comment by rtzoeller** [comment]
More information on .net standard 2.0 support for reflection.emit is available [here](https://github.com/dotnet/corefx/issues/29365)

**Comment by slozier** [comment]
Done in https://github.com/IronLanguages/ironpython3/pull/550
