### ISSUE TITLE
SyntaxError in variable unpacking

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#487]
```Python
for x, *y in (enumerate(range(5))): pass
```
> SyntaxError: invalid syntax

**Comment by hackf5** [comment]
This behaviour is described in [PEP 3132 -- Extended Iterable Unpacking](https://www.python.org/dev/peps/pep-3132/). The example given in this document is:

```python
for a, *b in [(1, 2, 3), (4, 5, 6, 7)]:
    print("a={0}, b={1}".format(a, b))
```
```
a=1, b=[2, 3]
a=4, b=[5, 6, 7]
```

**Comment by slozier** [comment]
Probably also of interest: https://github.com/IronLanguages/ironpython3/blob/master/Src/StdLib/Lib/test/test_unpack_ex.py

**Comment by hackf5** [comment]
Here are some more from `test_unpack_ex.py`
### Case 1
**Expected**
```python
[a, *b, c] = range(5)
print("a={0}, b={1}, c={2}".format(a, b, c))
```
```
a=0, b=[1, 2, 3], c=4
```

**Actual**
```
>>> [a, *b, c] = range(5)
  File "<stdin>", line 1
    [a, *b, c] = range(5)
        ^
SyntaxError: invalid syntax
```
### Case 2
**Expected**
```python
a, *b, c, *d, e = range(10)
```
```
SyntaxError: two starred expressions in assignment
```
**Actual**
```
>>> a, *b, c, *d, e = range(10)
>>> a
0
>>> b
[1, 2, 3, 4, 5, 6]
>>> c
7
>>> d
8
>>> e
9
```
### Case 3
**Expected**
```python
*a = range(10)
```
```
SyntaxError: starred assignment target must be in a list or tuple
```

**Actual**
```
>>> *a = range(10)
>>> a
range(0, 10)
```

### Case 4
**Expected**
```python
a* = range(10)
a*
```
```
    a* = range(10)
       ^
SyntaxError: invalid syntax
```
**Actual**
```
>>> a = range(1)
>>> *a
range(0, 1)
```
### Case 5
**Expected**
```python
*1
```
```
SyntaxError: can't use starred expression here
```
**Actual**
```
>>> *1
1
```

### Notes
There are a couple more failures in there, but they look like they are possibly handled by other cases, or they are valid but different messages for example `a, *b, c = [1]` gives an equivalent error message.

**Comment by hackf5** [comment]
The grammar definition for 3.4.10 is here: https://github.com/python/cpython/blob/v3.4.10/Grammar/Grammar
