### ISSUE TITLE
Make filter/map/zip classes

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#503]
Make `filter`/`map`/`zip` classes:
```Python
assert type(filter) is type
assert type(map) is type
assert type(zip) is type
```
Similarly to `enumerate` and `range`.

This is causing pickling errors in `test_builtin`.

**Comment by yuhan0** [comment]
I'd like to try to help with this - should the classes be placed in separate `Map.cs`, `Filter.cs`, `Zip.cs` files in the IronPython.Runtime namespace?

**Comment by slozier** [comment]
I think that would be fine. All the other builtin classes appear to be there as well.
