### ISSUE TITLE
round of an integer should return an integer

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#505]
```Python
x = 111111111111111111111111111111
assert round(x) == x
assert round(x, 2) == x
```
See https://github.com/IronLanguages/ironpython3/blob/master/WhatsNewInPython31.md

Also `round` with no `ndigits` argument always returns an `int`:
```Python
x = 1e16
assert type(round(x)) == type(int(x)) # using type(int(x)) since we haven't unified int/long yet
```

**Comment by rtzoeller** [comment]
There are a few other differences with `round` between Python 2 and 3 that I wasn't able to find tracked anywhere for IronPython, so I am adding them here. If you'd prefer separate issues, I am happy to create them.

- Incorrect message when `round` is called with `ndigits` as a float (e.g. `round(0, 0.)`)
  - Python 2 (and IronPython 3): `TypeError: 'float' object cannot be interpreted as an index`
  - Python 3: `TypeError: 'float' object cannot be interpreted as an integer`
- `round(myobject, ndigits)` should delegate to `myobject.__round__(ndigits)` for general Python objects
  - Current behavior results in `TypeError: expected float, got MyClassName`

**Comment by slozier** [comment]
Also:
- Python 2: if two multiples are equally close, rounding is done away from 0
- Python 3: if two multiples are equally close, rounding is done toward the even choice

**Comment by hackf5** [comment]
I'm having a go at this. So far seems fiddly, but doable. However I need to make an update to the DLR submodule to provide a new rounding method and this is causing me some level of misery as Git is telling me that I have a detached branch in the submodule. I have been working in a branch, not master, which might be the cause of the issues.

![image](https://user-images.githubusercontent.com/48881437/67167641-3ddb4380-f394-11e9-9b86-6ba0e7b6681d.png)

I've tried reading this https://stackoverflow.com/questions/18770545/why-is-my-git-submodule-head-detached-from-master but it isn't making much sense.

Does anyone have any pointers? I'm not very familiar with Git (too long in a big company).

**Comment by slozier** [comment]
@hackf5 Hmm, not sure. The DLR is a separate repo and you need a separate branch inside it. I usually do all my git stuff from the command line. From the command line I would go in the ironpython3\Src\DLR folder then `git checkout -b my_branch`. I would then do a PR in the DLR repo with my changes, get it merged in, then checkout the master branch of the DLR repo (with my changes merged in) and `git add Src\DLR` to the ironpython3 repo. Not sure if any of this helps...

One thing to consider is just putting the round helper methods in the ironpython3 repo directly instead of adding to submodule. Ideally we could just use the `Math.Round` methods directly.

**Comment by hackf5** [comment]
Thanks, I think I've got it sorted now.

I'd already spent about an hour trying to update my fork. It was failing to push to GitHub because there had been a change to an action and apparently I needed to push it using an appropriately permissioned access token.

**Comment by hackf5** [comment]
I think I've got this all working now, but my pull request has been rejected because of a failed DLR submodule update.

Do I need to submit this DLR pull request first?

**Comment by slozier** [comment]
@hackf5 Yes, unfortunately you'll need to submit the changes to the DLR repo first, wait for it to get merged in, then pull the DLR changes from master and submit a PR with that.

I do have some feedback on the rounding stuff in DLR. I would personally prefer having a signature like:
```C#
public static double Round (double value, int digits, MidpointRounding mode);
```
that way we can share code and obsolete the `RoundAwayFromZero` version.

**Comment by hackf5** [comment]
OK, so having made that method obsolete I can see it was also being used in FloatOps string formatting. The thing is that in CPython `"{:.1g}".format(2.5)` returns `2`, which means it is using the new rounding.

However, I have some issues with the `test_strformat.py` tests 😢. It seems that when they fail, the only thing they say is:

```
  Message: 
      Expected: 0
      But was:  1
    
  Stack Trace: 
    TestMethodCommand.Execute(TestExecutionContext context)
    SimpleWorkItem.PerformWork()
```
Any ideas why this would be and how it could be fixed? It is almost impossible to work on them with no information as to the cause of failure.

I think all you will need to do to see this is go into the file and break one of the tests.

**Comment by hackf5** [comment]
I'm running them through the test runner in the latest version of VS 2019.

**Comment by slozier** [comment]
Agreed that the test runner output is less than ideal. You can run the test file directly from `IronPythonConsole` to get the Python output. Set the application arguments (Properties->Debug) of the project to point to the script file.

**Comment by BCSharp** [comment]
What I do to see all details of a failing test is running it directly with `ipy.exe` from command line. For instance, on Windows:

```
PS> cd Tests
PS> ..\bin\Release\net45\ipy.exe test_strformat.py
```

**Comment by slozier** [comment]
Follow-up to @BCSharp's suggestion: You may also need to set an IRONPYTHONPATH environment variable to point to the Src\StdLib\Lib folder if you use the Release build from the command line (Debug build will automagically find it).

**Comment by hackf5** [comment]
Ah, that's perfect, thanks. I can work on the tests now 😄.

I now understand that Expected 0 means expected zero test failures. I had been interpreting it differently...

The other tests had spoiled me because they ran through the test window and reported back their errors correctly. How come these test aren't doing that?

**Comment by hackf5** [comment]
I've now moved all of the rounding logic into `__round__` methods declared in `FloatOps`, `LongOps` and `IntOps` so a call to round always routes to this special method.

I've also implemented the new rounding logic in the `float` string format method. I've not done anything for string formatting of `long` and `int`, looking at the code this might be OK.

While working on this I found this issue: https://github.com/IronLanguages/ironpython3/issues/658. I was partially handling this in the round code, which was completely wrong, so I've removed it.

**Comment by slozier** [comment]
@hackf5 Thanks, probably best to continue the discussion in https://github.com/IronLanguages/ironpython3/pull/656. Make it easier to follow what's going on. 😄

**Comment by hackf5** [comment]
OK, will do.

**Comment by slozier** [comment]
Round of int returns an int is fixed in, https://github.com/IronLanguages/ironpython3/pull/656.

The second part of the initial issue is the same as https://github.com/IronLanguages/ironpython3/issues/659 and we can use that to track it.
