### ISSUE TITLE
Can it be officially used?

### ISSUE THREAD

**Issue by jinyuttt** [IronLanguages/ironpython3#512]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `ipy -V`.

**Comment by jinyuttt** [comment]
Can it be officially used?

**Comment by slide** [comment]
No, please read the template when trying to open an issue. It specifically says that this is not the place to ask questions.

"The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at
https://ironpython.groups.io/g/users."
