### ISSUE TITLE
is it completely in managed code?

### ISSUE THREAD

**Issue by emersont1** [IronLanguages/ironpython3#57]
Hi

I think the title explains it all, also a question of stability
Many thanks

**Comment by jdhardy** [comment]
Yes, it is completely managed code. Some of the standard library shims
(like _msvcrt) use P/Invoke calls.

IronPython3 is not likely to be very usable right now; time has not allowed
for much work on it.

**Comment by simplicbe** [comment]
Question seems to be answered.
