### ISSUE TITLE
how do use dedupe in C# code ?

### ISSUE THREAD

**Issue by omansak** [IronLanguages/ironpython3#592]
I must make a Web Service with .Net that should communication to dedupe (https://github.com/dedupeio/dedupe)

I used IronPython and i got import 'No Module Named builtins'
I used PythonNet and i got System.DllNotFoundException: 'DLL 'python27' not load.
Visual Studio 2017 (15.9)
Python (3.5 or 3.7 and 2.7)
PythonNet last version build from master branch (Python.Runtime.dll)

I tried a lot of things and i failed all time. I couldn't connect with .net and python , always get errors.

I need run a function from py file to returns data. How do i make ?

my .py file

```
import sys
sys.path.append("C:\\Users\\**\\AppData\\Local\\\\Programs\\Python\\Python37-32\\python37.zip")            
sys.path.append("C:\\Users\\**\\AppData\\Local\\Programs\\Python\\Python37-32\\DLLs")             
sys.path.append("C:\\Users\\**\\AppData\\Local\\Programs\\Python\\Python37-32\\lib")               
sys.path.append("C:\\Users\\**\\AppData\\Local\\Programs\\Python\\Python37-32")               
sys.path.append("C:\\Users\\**\\AppData\\Roaming\\Python\\Python37\\site-packages")                
sys.path.append("C:\\Users\\**\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages")
sys.path.append("C:\\Users\\**\\Desktop\\Files\\dedupe-master\dedupe")

import csv
import re
import dedupe
from unidecode import unidecode


def readData(filename):
.....
```

**Comment by lostmsu** [comment]
This is not really the right repository to ask in. Your question appears to be about https://github.com/pythonnet/pythonnet/

Anyway, you need to ensure, that the directory, where you have `python27.dll` is listed in your PATH. See https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10

**Comment by slozier** [comment]
Unfortunately `dedupe` has a dependency on `numpy` so it won't work with IronPython.
