### ISSUE TITLE
IronPython 3 should use >= .Net 4.5.1 

### ISSUE THREAD

**Issue by simplicbe** [IronLanguages/ironpython3#69]
From my point of view, it would be enough if IronPython 3.x only supports .net framework version equal-greater than 4.5.1. This may make the build and test-process more easy.

**Comment by FluxIX** [comment]
Why specifically 4.5.1?

**Comment by slide** [comment]
We need to make sure that we are at a base that will work on Mono on Linux and MacOS. So, we need to determine what the most common distros have. We should also look at .NET Core.

**Comment by lafrank** [comment]
I still need to support Windows 2003 based servers so I'd vote on 4.0. But what feature would make 4.5.1 necessary ?

**Comment by jdhardy** [comment]
4.5 has the Task libraries built-in, which would be very handy for working
with asyncio. I think there's shims for 4.0 but using them is painful -
there's similar shims already to support BigInteger on .NET 2 and it makes
the code very ugly.

**Comment by simplicbe** [comment]
Yes, the TPL is a very good argument...

**Comment by hokb** [comment]
+1 for 4.5.1. Or even better: 4.5.2. because Microsoft has ended support for 4.0 anyway. https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/ 
Of course this will not release us of having to evaluate the set of common features among all supported platforms though.

**Comment by hokb** [comment]
@lafrank why not update it to a more recent framework on the server?

**Comment by markusschaber** [comment]
AFAICS, most of the TPL was already there in .NET 4.0, and there are backports which allow the "async" and "await" to work in .NET 4.0: 

> "The "Async Targeting Pack for Visual Studio 2012" enables projects targeting .NET Framework 4.0 or Silverlight 5 to use the Async language feature in C# 5 and Visual Basic 11. This pack requires Visual Studio 2012 and will not work with Visual Studio 2010."

https://www.microsoft.com/en-us/download/details.aspx?id=29576&wa=wsignin1.0
https://www.nuget.org/packages/Microsoft.CompilerServices.AsyncTargetingPack

There's also a free reimplementation:
https://gist.github.com/dgrunwald/1961087

So if it's just about the TPL, this is not a strict requirement of .NET 4.5. (And, if necessary, we could provide 2 different builds...)

On the other hand, +1 for supporting .NET Core, and also +1 for dropping SilverLight and .NET 2 / 3 (as long as we don't leave mono behind)...

**Comment by simplicbe** [comment]
@hokb because Windows Server 2003 does not support any newer versions than 4.0

**Comment by hokb** [comment]
Got it. How long are you planning on holding back a server upgrade? Often such incompatibilities serve as the best (only) argument to push the needed upgrade through, finally ;)

**Comment by lafrank** [comment]
@hokb, unfortunately in production, data center environments things are not going quickly if even were possible :-( Especially if we are talking about a shared management server running a dozen of another application...
And yes, as simplicbe pointed out, this case upgrading .NET is not a option.

**Comment by hokb** [comment]
Right, commonly such upgrades are hold back until it is simply not working anymore. But then suddenly things start moving rather quickly.

**Comment by hokb** [comment]
Right, commonly such upgrades are hold back until it is simply not working anymore. But then suddenly things start moving rather quickly.

**Comment by markusschaber** [comment]
@lafrank: Just playing the devils' advocate: If you cannot upgrade your OS, nor your .NET Framework: Who pushes you to upgrade IronPython to Python 3?

**Comment by lafrank** [comment]
@markusschaber : a due question indeed :-)
In fact, no one pushes me except myself. I wrote an application to script more than 50000 Cisco routers (PrettyGoodTerminal) as it was necessary to complete my job.
At my workplace I can only use a w2k3 server and currently upgrading is not an option.

On the other hand, as the application has become quite popular I decided to make it a public product available for anyone and there is a demand to support Py3 for the public. And I do not like the idea too much of running two editions of the app in parallel (Py2/.Net4 and Py3/.Net4+ compatible). 

But at the end of the day, I will accommodate to whatever version the final release would support.

**Comment by markusschaber** [comment]
There are several projects maintaining compatibility to both Python 2 and 3 using the same source base, with tools like six, 2to3 or 3to2. Maybe those could be an option.

That said, I personally prefer .NET 4.0 (for now), but I won't mind if we go up to .NET 4.5.x

**Comment by FluxIX** [comment]
I would prefer to stay at .NET 4.0 (Client profile, preferably).

**Comment by simplicbe** [comment]
@FluxIX have you tried to compile the Dlr using .Net Client Profile? I'm not sure whether this works or not. Could you check this?

**Comment by markusschaber** [comment]
I just tried to build the "Debug" target while setting the Client profile. The Microsoft.Scripting.AspNet and Chiron assemblies failed, everything else built fine.

**Comment by simplicbe** [comment]
I don't know how long we should support Chiron, Who is using it?

**Comment by markusschaber** [comment]
I'd say we keep it in 2.7, and drop it in 3.x - if someone really needs it, we can always revive it.

**Comment by jschementi** [comment]
It's for Silverlight development. So, it's safe to kill when Silverlight
support is dropped. Which is do immediately, but totally up to you ;)

**Comment by markusschaber** [comment]
So my suggestion is: (at least for builds targetting 4.0)
- Compile Chiron against the "normal" framework flavourin 2.7, and drop it in 3.x.
- Compile Microsoft.Scripting.AspNet against the "normal" framework flavour.
- Compile everything else gainst the "Client" framework flavour

**Comment by slide** [comment]
I think we should get rid of silverlight support in ipy3. We could also consider not supporting a v2 target at all.

**Comment by slide** [comment]
v2 has been removed, Silverlight support will also be removed.

**Comment by slide** [comment]
Silverlight support has now been removed.

**Comment by slide** [comment]
FYI, the plan is to continue supporting 4.0 for now. We will at some point want to start leveraging features in newer versions of C#, so we'll have to revisit this then. We're currently making the 4.5 build the default, with a 4.0 as secondary, similar to how v2 is secondary in IronPython2.

**Comment by markusschaber** [comment]
Just as a side note: Most newer C# features can still be used with older runtime versions.

For some other features, there are backports, like the "Async Targetting Pack" (https://www.microsoft.com/en-us/download/details.aspx?id=29576) for async / await, so we could require this pack for .NET 4.0, and use "native" support in .NET 4.5 builds.

I do not want to advocate in one or the other direction, just want to inform that there might be alternatives if we still need to support 4.0 at a time when we also need the new language features.
