### ISSUE TITLE
PEP328 - relative imports

### ISSUE THREAD

**Issue by lafrank** [IronLanguages/ironpython3#72]
I hope I am not missing a previous post again, but I realized IronPyhon does not understand relative imports with leading dots.

This is an outstanding issue, as it prevents IronPython to be effectively used with Cisco YDK-Py pacakge which favors relative imports.

**Comment by simplicbe** [comment]
We should take a look at the complete IronPython import mechanism. Several improvements should be done there. But thanks for filing this!

**Comment by slozier** [comment]
As far as I know this should work. If you have a specific example feel free to post it and we can reopen the issue.
