### ISSUE TITLE
windows compiler build fails for release45

### ISSUE THREAD

**Issue by chris-hawley** [IronLanguages/ironpython3#74]
In order to make it build, the solution needs to be updated so that the project uses an updated runtime. versions 4.6.1 and 4.5.2 worked for me. If this is not changed, the compiler fails to find all the dependencies.

**Comment by slide** [comment]
Can you post the build output?

**Comment by chris-hawley** [comment]
ok..so i think i found the root issue which is not what it appeared to be before. I tried moving from any cpu to x64 and it failed again. The reason it failed it because the .net versions across the projects were not the same.

**Comment by lafrank** [comment]
I updated runtime for all projects to 4.5.2, however still receiving the below compiler error on building with VS2015. Could you please help me what can be wrong with my settings as I believe the code should compile.

Error	CS1929	'EventTracker' does not contain a definition for 'GetAddMethod' and the best extension method overload 'ReflectionUtils.GetAddMethod(EventInfo, bool)' requires a receiver of type 'EventInfo'	IronPython	C:\My Projects\Visual Studio Projects\IronPython3\Src\IronPython\Runtime\Types\ReflectedEvent.cs	177

**Comment by lafrank** [comment]
Ok, solved it.
I realized the issue was that dlr references resolved to older (1.1.0.21) version dlls. After downloaded 1.2.0.0 and set reference paths for all projects to point to newer the dlr,  compilation succeeded.
