### ISSUE TITLE
Processing TracebackFrame

### ISSUE THREAD

**Issue by lafrank** [IronLanguages/ironpython3#75]
Based on [this ]( http://devhawk.net/blog/2009/10/7/hybrid-app-debugging-tracebackdelegate-and-settrace )article I develop a Python debugger in c# as part of my application.
At some point I need to get the current statement being executed in the actual frame.  Although the the line number is provided  (f_lineno) it is not enough as the traceback handler event also gets called for module files - not just the actual script - , and therefore one can't easily decide what code the line number is referring to.
I probably did not find the easy way (as did not find documentation), but it is quite complicated and relatively slow to access the necessary properties of the TracebackFrame to extract the source code. Reason is that  many of these properties are either protected or internal, and - ugly enough - I had to use reflection to dig them up, like 
```C#
    public string GetSourceCodeFromFrame(TraceBackFrame frame)
    {
      string result = "";
      try
      {
        Type tfCode = frame.f_code.GetType();
        PropertyInfo prop = tfCode.GetProperty("PythonCode", BindingFlags.NonPublic | BindingFlags.Instance);
        dynamic pAst = prop.GetValue(frame.f_code, null);
        prop = pAst.GetType().GetProperty("GlobalParent", BindingFlags.NonPublic | BindingFlags.Instance);
        dynamic gparent = prop.GetValue(pAst, null);
        prop = gparent.GetType().GetProperty("CompilerContext", BindingFlags.NonPublic | BindingFlags.Instance);
        CompilerContext context = prop.GetValue(gparent, null);
        result = context.SourceUnit.GetCode();
      }
      catch (Exception Ex)
      {
        Debug.WriteLine("Python debugger error : " + Ex.Message);
      }
      return result;
    }
```
My question is, whether it would be possible to make access to the currently executing statement - and not just line number - accessible easier ?

**Comment by simplicbe** [comment]
Make access to methods is possible. We should only keep in mind, that `public` stuff can't be removed or changes easily. Please make pull request with all required changes and we review them together. Can I close this issue with that answer? So Fork the project and make all required changes should be enough.

**Comment by lafrank** [comment]
You're overrating my knowledge of Ipy internals I am afraid :-) I even have
to catch up with git collaboration...
Anyway, I will try doing so, so you can close this issue, thank you.
