### ISSUE TITLE
On a clean build make fails on Windows (though VS succeeds)

### ISSUE THREAD

**Issue by iancooper** [IronLanguages/ironpython3#76]
On a clean git pull and make, the build fails with:

Program.cs(23,7): error CS0246: The type or namespace name 'IronPython' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\ian\oss\ironpython3\Src\IronPythonComp iler\IronPythonCompiler.csproj]

If I load the project into Visual Studio it then complains about NuGet.Config errors, but builds successfully once loaded.

Subsequent attempts to build with make fail with a new set of errors (that did not appear initially, only after a sucessful VS build). This may be due to the warnings as errors setting.

c:\Windows\Microsoft.NET\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll : error CS1684: Warning as Error: Reference to type 'System.Lazy`1' claims it i s defined in 'c:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll', but it could not be found [C:\Users\ian\oss\ironpython3\Src\IronPython.Wpf\IronPython.Wpf.csproj]
c:\Windows\Microsoft.NET\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll : error CS1684: Warning as Error: Reference to type 'System.Lazy`1' claims it i s defined in 'c:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll', but it could not be found [C:\Users\ian\oss\ironpython3\Src\IronPython.Wpf\IronPython.Wpf.csproj]
c:\Windows\Microsoft.NET\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll : error CS1684: Warning as Error: Reference to type 'System.Lazy`1' claims it i s defined in 'c:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll', but it could not be found [C:\Users\ian\oss\ironpython3\Src\IronPython.Wpf\IronPython.Wpf.csproj]
wpf.cs(38,55): error CS0246: The type or namespace name 'Clipboard' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\ian\oss\ironpython3\Src\IronPython.Wpf\Iro nPython.Wpf.csproj]

**Comment by slide** [comment]
Are you trying to build the v2Debug/v2Release configurations?

**Comment by iancooper** [comment]
I just ran make, with no params, as suggested in the readme

**Comment by slide** [comment]
Ok, I'll take a look very soon. Thanks for reporting the issue.

**Comment by sgulci** [comment]
hi, 
same here, my full console output

> D:\Open_Source\IronPython3>make
>   Installing 'NUnitLite 1.0.0'.
>   Installing 'DynamicLanguageRuntime 1.2.0-alpha1'.
>   Successfully installed 'NUnitLite 1.0.0'.
>   Successfully installed 'DynamicLanguageRuntime 1.2.0-alpha1'.
>   IronPython -> D:\Open_Source\IronPython3\bin\v2Debug\IronPython.dll
>   IronPython.Modules -> D:\Open_Source\IronPython3\bin\v2Debug\IronPython.Modules.dll
> C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this
>  reference. Could not locate the assembly "PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856a
> d364e35, ProcessorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by
> your code, you may get compilation errors. [D:\Open_Source\IronPython3\Src\IronPython.Wpf\IronPython.Wpf.csproj]
> c:\Windows\Microsoft.NET\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.d
> ll : error CS1684: Warning as Error: Reference to type 'System.Lazy`1' claims it is defined in 'c:\Windows\Microsoft.NE
> T\Framework\v2.0.50727\mscorlib.dll', but it could not be found [D:\Open_Source\IronPython3\Src\IronPython.Wpf\IronPyth
> on.Wpf.csproj]
> c:\Windows\Microsoft.NET\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.d
> ll : error CS1684: Warning as Error: Reference to type 'System.Lazy`1' claims it is defined in 'c:\Windows\Microsoft.NE
> T\Framework\v2.0.50727\mscorlib.dll', but it could not be found [D:\Open_Source\IronPython3\Src\IronPython.Wpf\IronPyth
> on.Wpf.csproj]
> c:\Windows\Microsoft.NET\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.d
> ll : error CS1684: Warning as Error: Reference to type 'System.Lazy`1' claims it is defined in 'c:\Windows\Microsoft.NE
> T\Framework\v2.0.50727\mscorlib.dll', but it could not be found [D:\Open_Source\IronPython3\Src\IronPython.Wpf\IronPyth
> on.Wpf.csproj]
> wpf.cs(38,55): error CS0246: The type or namespace name 'Clipboard' could not be found (are you missing a using directi
> ve or an assembly reference?) [D:\Open_Source\IronPython3\Src\IronPython.Wpf\IronPython.Wpf.csproj]
>   IronPythonConsole -> D:\Open_Source\IronPython3\bin\v2Debug\ipy.exe
>   IronPythonTest -> D:\Open_Source\IronPython3\bin\v2Debug\IronPythonTest.dll
>   IronPythonWindow -> D:\Open_Source\IronPython3\bin\v2Debug\ipyw.exe
>   IronPythonConsoleAny -> D:\Open_Source\IronPython3\bin\v2Debug\ipy64.exe
>   IronPythonWindowAny -> D:\Open_Source\IronPython3\bin\v2Debug\ipyw64.exe
>   IronPython.SQLite -> D:\Open_Source\IronPython3\bin\v2Debug\DLLs\IronPython.SQLite.dll
>   IronPythonTestConsole -> D:\Open_Source\IronPython3\bin\v2Debug\IronPythonTestConsole.exe
> Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to res
> olve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVers
> ion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://g
> o.microsoft.com/fwlink/?LinkId=291333.
>   IronPythonCompiler -> D:\Open_Source\IronPython3\bin\v2Debug\ipyc.exe

**Comment by simplicbe** [comment]
@sgulci Have you set the correct dlr path using the `batch` or `sh` file like descripted in the readme? After compiling and setting the correct dlr, it works in my case.

**Comment by sgulci** [comment]
@simplicbe it doesn't work for me

**Comment by slide** [comment]
This is fixed now, please verify.
