### ISSUE TITLE
Microsoft.Scripting.SyntaxErrorException: 'invalid syntax'

### ISSUE THREAD

**Issue by smittynusmc** [IronLanguages/ironpython3#785]
* [x] Are you running the latest version? Yes
* [x] Are you reporting to the correct repository? Yes
* [x] Did you perform a cursory search? Yes

### Description

Using IronPython3 to run a C# application. All I am doing right now is to ensure of the packages I need can import. All I have is below:

Python Code
...
import os
print("Hello")
...

C# Code
...
class Program
    {
        public static async Task Main(string[] args)
        {
           Model_Files filesStrings = new Model_Files();
            var engine = Python.CreateEngine();
            var scope = engine.CreateScope();
            ICollection<string> searchPaths = engine.GetSearchPaths();
            foreach (string path in searchPaths)
            {
                System.Console.Out.WriteLine(path);
            }
            System.Console.Out.WriteLine();
            
            // Now modify the search paths to include the directory
            // where the standard library has been installed
            
            var source = engine.CreateScriptSourceFromFile(filesStrings.scriptRelativePath);
            var compiled = source.Compile();
            var result = compiled.Execute(scope);
            // Other code after this nothing to do with error
          }
}
...
### Steps to Reproduce

1. filesStrings.scriptRelativePath is the path to the .py file in another project. I know it works because without any import statements the .py file runs fine with just a print("Hello")
2. I print the search paths to make sure I have the .py package files in the correct place
3. I run the program

**Expected behavior:** [I expect the program to run the .py file by importing os and printing hello

**Actual behavior:** 

I get the following error:

The error is thrown in Interpreter.cs on line 97

[SpecialName, MethodImpl(MethodImplOptions.NoInlining)]
        public void Run(InterpretedFrame frame) {
            while (true) {
                try {
                    var instructions = Instructions.Instructions;
                    int index = frame.InstructionIndex;
                    while (index < instructions.Length) {
                        index += instructions[index].Run(frame);
                        frame.InstructionIndex = index;
                    }
                    return;
                } catch (Exception exception) {
                    switch (HandleException(frame, exception)) {
                        **case ExceptionHandlingResult.Rethrow: throw;**
                        case ExceptionHandlingResult.Continue: continue;
                        case ExceptionHandlingResult.Return: return;
                    }
                }
            }
        }

Microsoft.Scripting.SyntaxErrorException: 'invalid syntax'

This exception was originally thrown at this call stack:
    Microsoft.Scripting.Interpreter.ThrowInstruction.Run(Microsoft.Scripting.Interpreter.InterpretedFrame) in ControlFlowInstructions.cs
    Microsoft.Scripting.Interpreter.Interpreter.HandleException(Microsoft.Scripting.Interpreter.InterpretedFrame, System.Exception) in Interpreter.cs
    Microsoft.Scripting.Interpreter.Interpreter.Run(Microsoft.Scripting.Interpreter.InterpretedFrame) in Interpreter.cs
    Microsoft.Scripting.Interpreter.LightLambda.Run2<T0, T1, TRet>(T0, T1) in LightLambda.Generated.cs
    IronPython.Compiler.PythonCallTargets.OriginalCallTarget1(IronPython.Runtime.PythonFunction, object) in PythonCallTargets.cs
    IronPython.Runtime.FunctionCaller<T0>.Call1(System.Runtime.CompilerServices.CallSite, IronPython.Runtime.CodeContext, object, T0) in PythonFunction.Generated.cs
    IronPython.Runtime.Method.MethodBinding.SelfTarget(System.Runtime.CompilerServices.CallSite, IronPython.Runtime.CodeContext, object) in Method.Generated.cs
    [External Code]
    IronPython.Runtime.FunctionCaller.Call0(System.Runtime.CompilerServices.CallSite, IronPython.Runtime.CodeContext, object) in PythonFunction.Generated.cs
    IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(Microsoft.Scripting.Interpreter.InterpretedFrame) in CallExpression.cs
    ...
    [Call Stack Truncated]

**The source code that it says has a invalid syntax says that is in **

C:\Users\adam.a.tucker1\source\repos\ml_test\myproject\bin\Debug\Lib\_collections_abc.py

T error details says the error is in the line:

        return await self.asend(None) 

### Versions
Visual Studio Community 2019
Python 3.6
IronPython3

**Comment by slozier** [comment]
Our current goal is to catch up to CPython 3.4. Since async/await is a 3.5 feature (https://github.com/IronLanguages/ironpython3/issues/98) it has not yet been implemented.

**Comment by smittynusmc** [comment]
Awesome! I will try to use Python 3.3. Hopefully that will work. Thanks for the quick response.
