### ISSUE TITLE
How to properly debug in a hosted envioronment?

### ISSUE THREAD

**Issue by interdrift** [IronLanguages/ironpython3#81]
I'm using 2.7.5 IronPython from NuGet, and running WPF 4.5.1

I've been trying to get debugging while executing the script in a hosted environment for the past month or so ( I expose some variables from my C# project to the script and use the variables inside it).It would be awesome to be able to debug using python tools for visual studio. Is there any way to do this correctly?

Looked here : http://stackoverflow.com/questions/676188/debugging-ironpython-scripts-in-hosted-embedded-environment

I tried using this :
```
   Dictionary<string, object> options = new Dictionary<string, object>();
   options["Debug"] = true;
   engine = Python.CreateEngine(options);
```
But it didn't work, VS still can't find any debugging symbols ( pdb file I assume )

As much as I know, IronPython doesn't generate any debugging symbols by default.

P.S I have disabled 'Just my code'

**Comment by slide** [comment]
Please use the Ironpython users mailing list for questions.

**Comment by simplicbe** [comment]
Or just usw stackoverflow

**Comment by interdrift** [comment]
This was more like a proposition for a wiki page)
