### ISSUE TITLE
long true division lacks precision for very large values

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#844]
Causes a failure in test_fractions
```Python
assert int('2'*400+'7') / int('3'*400+'1') == 2 / 3
```

**Comment by slozier** [comment]
Also causes failures in `test_shift_data_exact` of `CPython.test_statistics`.

**Comment by jameslan** [comment]
`test_shift_data_exact` seems not related to `BigInteger`, as those values (`10**9+16` etc) are in 32 bits int range

**Comment by slozier** [comment]
@jameslan I guess I should have provided a more concrete example. `test_shift_data_exact` ends up producing fractions such as `Fraction(151246562239730615230750785535999, 7130534626283790383418955530240)` and then converts them to `float`. The float conversion for fractions is just applying the division operations so the assert ends up essentially being:
```
assert 151246562239730615230750785535999 / 7130534626283790383418955530240 == 21.211111111111112
```
