### ISSUE TITLE
ironpython 2.7 : exposing a dynamic object to python unexpected behavior

### ISSUE THREAD

**Issue by interdrift** [IronLanguages/ironpython3#85]
If I try to expose an anonymous object to a python script through a hosted environment, I cannot access the members of the provided variable through python, it throws a MissingMemberException.

**Comment by simplicbe** [comment]
Would you like to add a simple project/sample, that makes your issue reproducable?

**Comment by interdrift** [comment]
@simplicbe  Sure, working on it

**Comment by slide** [comment]
This needs to be filed in the "main" repository, not ironpython3.
