### ISSUE TITLE
sys.builtin_module_names should be sorted

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#875]
```Python
assert sys.builtin_module_names == tuple(sorted(sys.builtin_module_names))
```

**Comment by syn2083** [comment]
I notice there isn't a test in the StdLib test_sys.py for this currently, would you want one added to diverge from CPython standard testing, or have this added elsewhere, or as a known background addition that is self validated?

Apologies if this is a lame question..

**Comment by slozier** [comment]
It's a great question. Tests that are not in the standard CPython library go in `Tests` folder. In this case a good place for this would be https://github.com/IronLanguages/ironpython3/blob/master/Tests/modules/system_related/test_sys.py

**Comment by syn2083** [comment]
Aha, thank you for that, I was browsing around, and had seen some of the different test locations, but was unsure of where. Ok, thank you!
