### ISSUE TITLE
Replace assertUnreachable with fail

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#880]
`assertUnreachable` was removed in https://github.com/IronLanguages/ironpython3/pull/561 and should be replaced with `fail` in tests.

**Comment by komodo472** [comment]
I'm trying to work on this issue and I'm wondering if using `Tests/run.py` is still the preferred way to run the python tests under `Tests`? If not, what is the preferred way to test this issue to see if I got it working?

**Comment by slozier** [comment]
Preferred way to run all tests is via `pwsh make.ps1 test-all`. You can also run a specific test with `test-something`. Although this one is kind of hard to test since by definition the code should be unreachable. :smile:
