### ISSUE TITLE
Cannot use pickle module in ironpython3

### ISSUE THREAD

**Issue by bigsuntat** [IronLanguages/ironpython3#935]
Hi, Everyone

I can not use pickle load model python file please add

**Comment by bigsuntat** [comment]
Yes,

**Comment by slozier** [comment]
It's hard to tell from your example, but I assume you're getting an `ImportError`? Something like:
> ImportError: No module named 'something'

This is not an issue with `pickle.load` but a missing 3rd party module. If it's not an `ImportError` then it would be helpful to have a sample `model.sav` so the issue can be reproduced.

**Comment by bigsuntat** [comment]
Have your email, please tell me I will send my model
