### ISSUE TITLE
sys.executable is not executable with Mono

### ISSUE THREAD

**Issue by jameslan** [IronLanguages/ironpython3#937]
With Mono, `sys.executable` returns `/absolute/path/to/ipy.exe`, which can't be directly executed, but needs to be run by mono: `mono ipy.exe`. This makes `subprocess.Popen([sys.executable])` fail.

On the contrary, with .NET Core, `sys.executable` returns the shell wrapper, which could be launched directly. Thus `subprocess.Popen([sys.executable])` succeeds.

**Comment by slozier** [comment]
We could add some Mono shell wrappers and do a runtime check when setting `sys.executable`.
