### ISSUE TITLE
Assertion error when running test_bytes in debug mode

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#955]
`test_bytes.test_dunder_index` raises a .NET assertion error when run in `Debug` mode. Haven't looked at the details.

@BCSharp

**Comment by BCSharp** [comment]
This reduces to the following:

```python
class A(str): pass
getattr(A(), '__iter__')
```
CPython produces `<method-wrapper '__iter__' of A object at 0x0000000003F384F8>` (a factory for an iterator of 0 length).
IronPython (release) throws `AttributeError: 'A' object has no attribute '__iter__'`
IronPython (debug) hits `Debug.Assert(false)` at `PythonTypes.cs:523`
