### ISSUE TITLE
Subclasses of str missing __iter__ attribute

### ISSUE THREAD

**Issue by BCSharp** [IronLanguages/ironpython3#957]
```python
class A(str): pass
getattr(A("abc"), '__iter__')
```

CPython produces `<method-wrapper '__iter__' of A object at 0x00000000031584F8>` (a factory for an iterator of length 3).
IronPython (release) throws `AttributeError: 'A' object has no attribute '__iter__'`
IronPython (debug) hits `Debug.Assert(false)` at PythonTypes.cs:523

Originally discovered during analysis of #955.

**Comment by slozier** [comment]
This got resolved by https://github.com/IronLanguages/ironpython3/pull/1088
