### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation no longer allowed

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#982]
Inconsistent use of tabs and spaces in indentation is no longer allowed. With Python 2 this was allowed, but could be guarded again using the -t (or -tt) command line argument.

This should always throw:
```Python
compile("try:\n\t1/0\n    \t1/0\nfinally:\n pass\n", '<string>', 'exec')
```

Things to do:
- [ ] Ignore `-t` and `-tt` command line arguments
- [ ] Remove `-t` and `-tt` from command line help
- [ ] Remove `sys.flags.tabcheck`
- [ ] Remove `PythonOptions.IndentationInconsistencySeverity` and related code

**Comment by BCSharp** [comment]
> Remove `-t` and `-tt` command line arguments

I think better than remove is to ignore, like [CPython does](https://github.com/python/cpython/blob/b81c833ab51fb7d7f0f8eaace37f60ef7455aa85/Python/initconfig.c#L2002):

```C
        case 't':
            /* ignored for backwards compatibility */
            break;
```

**Comment by slozier** [comment]
Fine by me. Will amend to "remove from command line help".

**Comment by slozier** [comment]
Fixed by https://github.com/IronLanguages/ironpython3/pull/1131
